# flake8: noqa
from app.docs.api_docs.content.block import BLOCK_ENDPOINTS, UNICODE_BLOCK_OBJECT_INTRO, UNICODE_BLOCK_OBJECT_PROPERTIES
from app.docs.api_docs.content.character import (
    CHARACTER_ENDPOINTS,
    PROP_GROUP_BASIC,
    PROP_GROUP_BIDIRECTIONALITY,
    PROP_GROUP_CASE,
    PROP_GROUP_CJK_VARIANTS,
    PROP_GROUP_DECOMPOSITION,
    PROP_GROUP_EAW,
    PROP_GROUP_EMOJI,
    PROP_GROUP_F_AND_G,
    PROP_GROUP_HANGUL,
    PROP_GROUP_INDIC,
    PROP_GROUP_JOINING,
    PROP_GROUP_LINEBREAK,
    PROP_GROUP_MINIMUM,
    PROP_GROUP_NUMERIC,
    PROP_GROUP_QUICK_CHECK,
    PROP_GROUP_SCRIPT,
    PROP_GROUP_UTF8,
    PROP_GROUP_UTF16,
    PROP_GROUP_UTF32,
    UNICODE_CHARACTER_PROP_GROUPS_CONTINUED_1,
    UNICODE_CHARACTER_PROP_GROUPS_CONTINUED_2,
    UNICODE_CHARACTER_PROP_GROUPS_INTRO,
    UNICODE_CHATACTER_OBJECT_INTRO,
    VERBOSITY,
)
from app.docs.api_docs.content.intro import (
    INTRODUCTION,
    LOOSE_MATCHING,
    PAGINATION,
    PROJECT_LINKS_README,
    PROJECT_LINKS_SWAGGER_HTML,
    SEARCH,
)
from app.docs.api_docs.content.plane import PLANE_ENDPOINTS, UNICODE_PLANE_OBJECT_INTRO, UNICODE_PLANE_OBJECT_PROPERTIES
