import re
from enum import IntEnum


class UnicodeBlock(IntEnum):

    NONE = 0
    BASIC_LATIN = 1
    LATIN_1_SUPPLEMENT = 2
    LATIN_EXTENDED_A = 3
    LATIN_EXTENDED_B = 4
    IPA_EXTENSIONS = 5
    SPACING_MODIFIER_LETTERS = 6
    COMBINING_DIACRITICAL_MARKS = 7
    GREEK_AND_COPTIC = 8
    CYRILLIC = 9
    CYRILLIC_SUPPLEMENT = 10
    ARMENIAN = 11
    HEBREW = 12
    ARABIC = 13
    SYRIAC = 14
    ARABIC_SUPPLEMENT = 15
    THAANA = 16
    NKO = 17
    SAMARITAN = 18
    MANDAIC = 19
    SYRIAC_SUPPLEMENT = 20
    ARABIC_EXTENDED_B = 21
    ARABIC_EXTENDED_A = 22
    DEVANAGARI = 23
    BENGALI = 24
    GURMUKHI = 25
    GUJARATI = 26
    ORIYA = 27
    TAMIL = 28
    TELUGU = 29
    KANNADA = 30
    MALAYALAM = 31
    SINHALA = 32
    THAI = 33
    LAO = 34
    TIBETAN = 35
    MYANMAR = 36
    GEORGIAN = 37
    HANGUL_JAMO = 38
    ETHIOPIC = 39
    ETHIOPIC_SUPPLEMENT = 40
    CHEROKEE = 41
    UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS = 42
    OGHAM = 43
    RUNIC = 44
    TAGALOG = 45
    HANUNOO = 46
    BUHID = 47
    TAGBANWA = 48
    KHMER = 49
    MONGOLIAN = 50
    UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED = 51
    LIMBU = 52
    TAI_LE = 53
    NEW_TAI_LUE = 54
    KHMER_SYMBOLS = 55
    BUGINESE = 56
    TAI_THAM = 57
    COMBINING_DIACRITICAL_MARKS_EXTENDED = 58
    BALINESE = 59
    SUNDANESE = 60
    BATAK = 61
    LEPCHA = 62
    OL_CHIKI = 63
    CYRILLIC_EXTENDED_C = 64
    GEORGIAN_EXTENDED = 65
    SUNDANESE_SUPPLEMENT = 66
    VEDIC_EXTENSIONS = 67
    PHONETIC_EXTENSIONS = 68
    PHONETIC_EXTENSIONS_SUPPLEMENT = 69
    COMBINING_DIACRITICAL_MARKS_SUPPLEMENT = 70
    LATIN_EXTENDED_ADDITIONAL = 71
    GREEK_EXTENDED = 72
    GENERAL_PUNCTUATION = 73
    SUPERSCRIPTS_AND_SUBSCRIPTS = 74
    CURRENCY_SYMBOLS = 75
    COMBINING_DIACRITICAL_MARKS_FOR_SYMBOLS = 76
    LETTERLIKE_SYMBOLS = 77
    NUMBER_FORMS = 78
    ARROWS = 79
    MATHEMATICAL_OPERATORS = 80
    MISCELLANEOUS_TECHNICAL = 81
    CONTROL_PICTURES = 82
    OPTICAL_CHARACTER_RECOGNITION = 83
    ENCLOSED_ALPHANUMERICS = 84
    BOX_DRAWING = 85
    BLOCK_ELEMENTS = 86
    GEOMETRIC_SHAPES = 87
    MISCELLANEOUS_SYMBOLS = 88
    DINGBATS = 89
    MISCELLANEOUS_MATHEMATICAL_SYMBOLS_A = 90
    SUPPLEMENTAL_ARROWS_A = 91
    BRAILLE_PATTERNS = 92
    SUPPLEMENTAL_ARROWS_B = 93
    MISCELLANEOUS_MATHEMATICAL_SYMBOLS_B = 94
    SUPPLEMENTAL_MATHEMATICAL_OPERATORS = 95
    MISCELLANEOUS_SYMBOLS_AND_ARROWS = 96
    GLAGOLITIC = 97
    LATIN_EXTENDED_C = 98
    COPTIC = 99
    GEORGIAN_SUPPLEMENT = 100
    TIFINAGH = 101
    ETHIOPIC_EXTENDED = 102
    CYRILLIC_EXTENDED_A = 103
    SUPPLEMENTAL_PUNCTUATION = 104
    CJK_RADICALS_SUPPLEMENT = 105
    KANGXI_RADICALS = 106
    IDEOGRAPHIC_DESCRIPTION_CHARACTERS = 107
    CJK_SYMBOLS_AND_PUNCTUATION = 108
    HIRAGANA = 109
    KATAKANA = 110
    BOPOMOFO = 111
    HANGUL_COMPATIBILITY_JAMO = 112
    KANBUN = 113
    BOPOMOFO_EXTENDED = 114
    CJK_STROKES = 115
    KATAKANA_PHONETIC_EXTENSIONS = 116
    ENCLOSED_CJK_LETTERS_AND_MONTHS = 117
    CJK_COMPATIBILITY = 118
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_A = 119
    YIJING_HEXAGRAM_SYMBOLS = 120
    CJK_UNIFIED_IDEOGRAPHS = 121
    YI_SYLLABLES = 122
    YI_RADICALS = 123
    LISU = 124
    VAI = 125
    CYRILLIC_EXTENDED_B = 126
    BAMUM = 127
    MODIFIER_TONE_LETTERS = 128
    LATIN_EXTENDED_D = 129
    SYLOTI_NAGRI = 130
    COMMON_INDIC_NUMBER_FORMS = 131
    PHAGS_PA = 132
    SAURASHTRA = 133
    DEVANAGARI_EXTENDED = 134
    KAYAH_LI = 135
    REJANG = 136
    HANGUL_JAMO_EXTENDED_A = 137
    JAVANESE = 138
    MYANMAR_EXTENDED_B = 139
    CHAM = 140
    MYANMAR_EXTENDED_A = 141
    TAI_VIET = 142
    MEETEI_MAYEK_EXTENSIONS = 143
    ETHIOPIC_EXTENDED_A = 144
    LATIN_EXTENDED_E = 145
    CHEROKEE_SUPPLEMENT = 146
    MEETEI_MAYEK = 147
    HANGUL_SYLLABLES = 148
    HANGUL_JAMO_EXTENDED_B = 149
    HIGH_SURROGATES = 150
    HIGH_PRIVATE_USE_SURROGATES = 151
    LOW_SURROGATES = 152
    PRIVATE_USE_AREA = 153
    CJK_COMPATIBILITY_IDEOGRAPHS = 154
    ALPHABETIC_PRESENTATION_FORMS = 155
    ARABIC_PRESENTATION_FORMS_A = 156
    VARIATION_SELECTORS = 157
    VERTICAL_FORMS = 158
    COMBINING_HALF_MARKS = 159
    CJK_COMPATIBILITY_FORMS = 160
    SMALL_FORM_VARIANTS = 161
    ARABIC_PRESENTATION_FORMS_B = 162
    HALFWIDTH_AND_FULLWIDTH_FORMS = 163
    SPECIALS = 164
    LINEAR_B_SYLLABARY = 165
    LINEAR_B_IDEOGRAMS = 166
    AEGEAN_NUMBERS = 167
    ANCIENT_GREEK_NUMBERS = 168
    ANCIENT_SYMBOLS = 169
    PHAISTOS_DISC = 170
    LYCIAN = 171
    CARIAN = 172
    COPTIC_EPACT_NUMBERS = 173
    OLD_ITALIC = 174
    GOTHIC = 175
    OLD_PERMIC = 176
    UGARITIC = 177
    OLD_PERSIAN = 178
    DESERET = 179
    SHAVIAN = 180
    OSMANYA = 181
    OSAGE = 182
    ELBASAN = 183
    CAUCASIAN_ALBANIAN = 184
    VITHKUQI = 185
    LINEAR_A = 186
    LATIN_EXTENDED_F = 187
    CYPRIOT_SYLLABARY = 188
    IMPERIAL_ARAMAIC = 189
    PALMYRENE = 190
    NABATAEAN = 191
    HATRAN = 192
    PHOENICIAN = 193
    LYDIAN = 194
    MEROITIC_HIEROGLYPHS = 195
    MEROITIC_CURSIVE = 196
    KHAROSHTHI = 197
    OLD_SOUTH_ARABIAN = 198
    OLD_NORTH_ARABIAN = 199
    MANICHAEAN = 200
    AVESTAN = 201
    INSCRIPTIONAL_PARTHIAN = 202
    INSCRIPTIONAL_PAHLAVI = 203
    PSALTER_PAHLAVI = 204
    OLD_TURKIC = 205
    OLD_HUNGARIAN = 206
    HANIFI_ROHINGYA = 207
    RUMI_NUMERAL_SYMBOLS = 208
    YEZIDI = 209
    ARABIC_EXTENDED_C = 210
    OLD_SOGDIAN = 211
    SOGDIAN = 212
    OLD_UYGHUR = 213
    CHORASMIAN = 214
    ELYMAIC = 215
    BRAHMI = 216
    KAITHI = 217
    SORA_SOMPENG = 218
    CHAKMA = 219
    MAHAJANI = 220
    SHARADA = 221
    SINHALA_ARCHAIC_NUMBERS = 222
    KHOJKI = 223
    MULTANI = 224
    KHUDAWADI = 225
    GRANTHA = 226
    NEWA = 227
    TIRHUTA = 228
    SIDDHAM = 229
    MODI = 230
    MONGOLIAN_SUPPLEMENT = 231
    TAKRI = 232
    AHOM = 233
    DOGRA = 234
    WARANG_CITI = 235
    DIVES_AKURU = 236
    NANDINAGARI = 237
    ZANABAZAR_SQUARE = 238
    SOYOMBO = 239
    UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED_A = 240
    PAU_CIN_HAU = 241
    DEVANAGARI_EXTENDED_A = 242
    BHAIKSUKI = 243
    MARCHEN = 244
    MASARAM_GONDI = 245
    GUNJALA_GONDI = 246
    MAKASAR = 247
    KAWI = 248
    LISU_SUPPLEMENT = 249
    TAMIL_SUPPLEMENT = 250
    CUNEIFORM = 251
    CUNEIFORM_NUMBERS_AND_PUNCTUATION = 252
    EARLY_DYNASTIC_CUNEIFORM = 253
    CYPRO_MINOAN = 254
    EGYPTIAN_HIEROGLYPHS = 255
    EGYPTIAN_HIEROGLYPH_FORMAT_CONTROLS = 256
    ANATOLIAN_HIEROGLYPHS = 257
    BAMUM_SUPPLEMENT = 258
    MRO = 259
    TANGSA = 260
    BASSA_VAH = 261
    PAHAWH_HMONG = 262
    MEDEFAIDRIN = 263
    MIAO = 264
    IDEOGRAPHIC_SYMBOLS_AND_PUNCTUATION = 265
    TANGUT = 266
    TANGUT_COMPONENTS = 267
    KHITAN_SMALL_SCRIPT = 268
    TANGUT_SUPPLEMENT = 269
    KANA_EXTENDED_B = 270
    KANA_SUPPLEMENT = 271
    KANA_EXTENDED_A = 272
    SMALL_KANA_EXTENSION = 273
    NUSHU = 274
    DUPLOYAN = 275
    SHORTHAND_FORMAT_CONTROLS = 276
    ZNAMENNY_MUSICAL_NOTATION = 277
    BYZANTINE_MUSICAL_SYMBOLS = 278
    MUSICAL_SYMBOLS = 279
    ANCIENT_GREEK_MUSICAL_NOTATION = 280
    KAKTOVIK_NUMERALS = 281
    MAYAN_NUMERALS = 282
    TAI_XUAN_JING_SYMBOLS = 283
    COUNTING_ROD_NUMERALS = 284
    MATHEMATICAL_ALPHANUMERIC_SYMBOLS = 285
    SUTTON_SIGNWRITING = 286
    LATIN_EXTENDED_G = 287
    GLAGOLITIC_SUPPLEMENT = 288
    CYRILLIC_EXTENDED_D = 289
    NYIAKENG_PUACHUE_HMONG = 290
    TOTO = 291
    WANCHO = 292
    NAG_MUNDARI = 293
    ETHIOPIC_EXTENDED_B = 294
    MENDE_KIKAKUI = 295
    ADLAM = 296
    INDIC_SIYAQ_NUMBERS = 297
    OTTOMAN_SIYAQ_NUMBERS = 298
    ARABIC_MATHEMATICAL_ALPHABETIC_SYMBOLS = 299
    MAHJONG_TILES = 300
    DOMINO_TILES = 301
    PLAYING_CARDS = 302
    ENCLOSED_ALPHANUMERIC_SUPPLEMENT = 303
    ENCLOSED_IDEOGRAPHIC_SUPPLEMENT = 304
    MISCELLANEOUS_SYMBOLS_AND_PICTOGRAPHS = 305
    EMOTICONS = 306
    ORNAMENTAL_DINGBATS = 307
    TRANSPORT_AND_MAP_SYMBOLS = 308
    ALCHEMICAL_SYMBOLS = 309
    GEOMETRIC_SHAPES_EXTENDED = 310
    SUPPLEMENTAL_ARROWS_C = 311
    SUPPLEMENTAL_SYMBOLS_AND_PICTOGRAPHS = 312
    CHESS_SYMBOLS = 313
    SYMBOLS_AND_PICTOGRAPHS_EXTENDED_A = 314
    SYMBOLS_FOR_LEGACY_COMPUTING = 315
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_B = 316
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_C = 317
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_D = 318
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_E = 319
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_F = 320
    CJK_COMPATIBILITY_IDEOGRAPHS_SUPPLEMENT = 321
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_G = 322
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_H = 323
    TAGS = 324
    VARIATION_SELECTORS_SUPPLEMENT = 325
    SUPPLEMENTARY_PRIVATE_USE_AREA_A = 326
    SUPPLEMENTARY_PRIVATE_USE_AREA_B = 327

    def __str__(self):
        special_cases = {
            "LATIN_1_SUPPLEMENT": "Latin-1 Supplement",
            "LATIN_EXTENDED_A": "Latin Extended-A",
            "LATIN_EXTENDED_B": "Latin Extended-B",
            "ARABIC_EXTENDED_B": "Arabic Extended-B",
            "ARABIC_EXTENDED_A": "Arabic Extended-A",
            "CYRILLIC_EXTENDED_C": "Cyrillic Extended-C",
            "MISCELLANEOUS_MATHEMATICAL_SYMBOLS_A": "Miscellaneous Mathematical Symbols-A",
            "SUPPLEMENTAL_ARROWS_A": "Supplemental Arrows-A",
            "SUPPLEMENTAL_ARROWS_B": "Supplemental Arrows-B",
            "MISCELLANEOUS_MATHEMATICAL_SYMBOLS_B": "Miscellaneous Mathematical Symbols-B",
            "LATIN_EXTENDED_C": "Latin Extended-C",
            "CYRILLIC_EXTENDED_A": "Cyrillic Extended-A",
            "CYRILLIC_EXTENDED_B": "Cyrillic Extended-B",
            "LATIN_EXTENDED_D": "Latin Extended-D",
            "PHAGS_PA": "Phags-pa",
            "HANGUL_JAMO_EXTENDED_A": "Hangul Jamo Extended-A",
            "MYANMAR_EXTENDED_B": "Myanmar Extended-B",
            "MYANMAR_EXTENDED_A": "Myanmar Extended-A",
            "ETHIOPIC_EXTENDED_A": "Ethiopic Extended-A",
            "LATIN_EXTENDED_E": "Latin Extended-E",
            "HANGUL_JAMO_EXTENDED_B": "Hangul Jamo Extended-B",
            "ARABIC_PRESENTATION_FORMS_A": "Arabic Presentation Forms-A",
            "ARABIC_PRESENTATION_FORMS_B": "Arabic Presentation Forms-B",
            "LATIN_EXTENDED_F": "Latin Extended-F",
            "UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED_A": "Unified Canadian Aboriginal Syllabics Extended-A",
            "CYPRO_MINOAN": "Cypro-Minoan",
            "KANA_EXTENDED_B": "Kana Extended-B",
            "KANA_EXTENDED_A": "Kana Extended-A",
            "LATIN_EXTENDED_G": "Latin Extended-G",
            "ETHIOPIC_EXTENDED_B": "Ethiopic Extended-B",
            "SUPPLEMENTAL_ARROWS_C": "Supplemental Arrows-C",
            "SYMBOLS_AND_PICTOGRAPHS_EXTENDED_A": "Symbols and Pictographs Extended-A",
            "SUPPLEMENTARY_PRIVATE_USE_AREA_A": "Supplementary Private Use Area-A",
            "SUPPLEMENTARY_PRIVATE_USE_AREA_B": "Supplementary Private Use Area-B",
            "ARABIC_EXTENDED_C": "Arabic Extended-C",
            "DEVANAGARI_EXTENDED_A": "Devanagari Extended-A",
            "CYRILLIC_EXTENDED_D": "Cyrillic Extended-D",
        }
        if self.name in special_cases:
            return special_cases.get(self.name)
        name = (
            self.name.replace("_", " ")
            .title()
            .replace("Cjk", "CJK")
            .replace("And", "and")
            .replace("Ipa", "IPA")
            .replace("Nko", "NKo")
            .replace("Signwriting", "SignWriting")
        )
        return re.sub(r"For\b", "for", name)

    @property
    def display_name(self) -> str:
        return str(self)

    @property
    def block_id(self) -> int:
        return int(self)

    @classmethod
    def from_block_id(cls, id: int):
        return cls(id)
