SEARCH_TERM_OLD_PER_PAGE_5_PAGE_1_OF_2 = {
    "url": "/v1/blocks/search",
    "query": "old",
    "hasMore": True,
    "currentPage": 1,
    "nextPage": 2,
    "totalResults": 9,
    "results": [
        {
            "id": 174,
            "name": "Old Italic",
            "plane": "SMP",
            "start": "U+10300",
            "finish": "U+1032F",
            "totalAllocated": 48,
            "totalDefined": 39,
            "score": 90,
        },
        {
            "id": 176,
            "name": "Old Permic",
            "plane": "SMP",
            "start": "U+10350",
            "finish": "U+1037F",
            "totalAllocated": 48,
            "totalDefined": 43,
            "score": 90,
        },
        {
            "id": 178,
            "name": "Old Persian",
            "plane": "SMP",
            "start": "U+103A0",
            "finish": "U+103DF",
            "totalAllocated": 64,
            "totalDefined": 50,
            "score": 90,
        },
        {
            "id": 198,
            "name": "Old South Arabian",
            "plane": "SMP",
            "start": "U+10A60",
            "finish": "U+10A7F",
            "totalAllocated": 32,
            "totalDefined": 32,
            "score": 90,
        },
        {
            "id": 199,
            "name": "Old North Arabian",
            "plane": "SMP",
            "start": "U+10A80",
            "finish": "U+10A9F",
            "totalAllocated": 32,
            "totalDefined": 32,
            "score": 90,
        },
    ],
}

SEARCH_TERM_OLD_PER_PAGE_5_PAGE_2_OF_2 = {
    "url": "/v1/blocks/search",
    "query": "old",
    "hasMore": False,
    "currentPage": 2,
    "totalResults": 9,
    "results": [
        {
            "id": 205,
            "name": "Old Turkic",
            "plane": "SMP",
            "start": "U+10C00",
            "finish": "U+10C4F",
            "totalAllocated": 80,
            "totalDefined": 73,
            "score": 90,
        },
        {
            "id": 206,
            "name": "Old Hungarian",
            "plane": "SMP",
            "start": "U+10C80",
            "finish": "U+10CFF",
            "totalAllocated": 128,
            "totalDefined": 108,
            "score": 90,
        },
        {
            "id": 211,
            "name": "Old Sogdian",
            "plane": "SMP",
            "start": "U+10F00",
            "finish": "U+10F2F",
            "totalAllocated": 48,
            "totalDefined": 40,
            "score": 90,
        },
        {
            "id": 213,
            "name": "Old Uyghur",
            "plane": "SMP",
            "start": "U+10F70",
            "finish": "U+10FAF",
            "totalAllocated": 64,
            "totalDefined": 26,
            "score": 90,
        },
    ],
}

SEARCH_TERM_OLD_PER_PAGE_5_PAGE_3_OF_2 = {"detail": "Request for page #3 is invalid since there are 2 total pages."}

SEARCH_TERM_CAP = {
    "url": "/v1/blocks/search",
    "query": "cap",
    "hasMore": False,
    "currentPage": 0,
    "totalResults": 0,
    "results": [],
}
