FROM python:3.
SHELL ["/bin/bash", "-c"]

ARG ENV
ARG UNICODE_VERSION
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_DB
ARG REDIS_PW
ARG RATE_LIMIT_PER_PERIOD
ARG RATE_LIMIT_PERIOD_SECONDS
ARG RATE_LIMIT_BURST
ARG TEST_HEADER

ENV ENV=${ENV}
ENV UNICODE_VERSION=${UNICODE_VERSION}
ENV REDIS_HOST=${REDIS_HOST}
ENV REDIS_PORT=${REDIS_PORT}
ENV REDIS_DB=${REDIS_DB}
ENV REDIS_PW=${REDIS_PW}
ENV RATE_LIMIT_PER_PERIOD=${RATE_LIMIT_PER_PERIOD}
ENV RATE_LIMIT_PERIOD_SECONDS=${RATE_LIMIT_PERIOD_SECONDS}
ENV RATE_LIMIT_BURST=${RATE_LIMIT_BURST}
ENV TEST_HEADER=${TEST_HEADER}

WORKDIR /code

RUN echo $'ENV=${ENV}\n\
PYTHONPATH=.\n\
UNICODE_VERSION=${UNICODE_VERSION}\n\
REDIS_HOST=${REDIS_HOST}\n\
REDIS_PORT=${REDIS_PORT}\n\
REDIS_DB=${REDIS_DB}\n\
REDIS_PW=${REDIS_PW}\n\
RATE_LIMIT_PER_PERIOD=${RATE_LIMIT_PER_PERIOD}\n\
RATE_LIMIT_PERIOD_SECONDS=${RATE_LIMIT_PERIOD_SECONDS}\n\
RATE_LIMIT_BURST=${RATE_LIMIT_BURST}\n\
TEST_HEADER=${TEST_HEADER}' > /code/.env

RUN pip install -U pip setuptools wheel
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
EXPOSE 80
COPY ./app /code/app 
RUN PYTHONPATH=/code/. python /code/./app/data/scripts/get_prod_data.py
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
