ALL_PLANES = {
    "url": "/v1/planes",
    "totalResults": 7,
    "hasMore": False,
    "data": [
        {
            "number": 0,
            "name": "Basic Multilingual Plane",
            "abbreviation": "BMP",
            "start": "U+0000",
            "finish": "U+FFFF",
            "totalAllocated": 65536,
            "totalDefined": 55639,
        },
        {
            "number": 1,
            "name": "Supplementary Multilingual Plane",
            "abbreviation": "SMP",
            "start": "U+10000",
            "finish": "U+1FFFF",
            "totalAllocated": 65536,
            "totalDefined": 23276,
        },
        {
            "number": 2,
            "name": "Supplementary Ideographic Plane",
            "abbreviation": "SIP",
            "start": "U+20000",
            "finish": "U+2FFFF",
            "totalAllocated": 65536,
            "totalDefined": 61495,
        },
        {
            "number": 3,
            "name": "Tertiary Ideographic Plane",
            "abbreviation": "TIP",
            "start": "U+30000",
            "finish": "U+3FFFF",
            "totalAllocated": 65536,
            "totalDefined": 9131,
        },
        {
            "number": 14,
            "name": "Supplementary Special-purpose Plane",
            "abbreviation": "SSP",
            "start": "U+E0000",
            "finish": "U+EFFFF",
            "totalAllocated": 65536,
            "totalDefined": 337,
        },
        {
            "number": 15,
            "name": "Supplementary Private Use Area-A",
            "abbreviation": "SPUA-A",
            "start": "U+F0000",
            "finish": "U+FFFFF",
            "totalAllocated": 65536,
            "totalDefined": 0,
        },
        {
            "number": 16,
            "name": "Supplementary Private Use Area-B",
            "abbreviation": "SPUA-B",
            "start": "U+100000",
            "finish": "U+10FFFF",
            "totalAllocated": 65536,
            "totalDefined": 0,
        },
    ],
}

UNASSIGNED_PLANE = {
    "number": 10,
    "name": "Unassigned Plane",
    "abbreviation": "N/A",
    "start": "U+A0000",
    "finish": "U+AFFFF",
    "totalAllocated": 0,
    "totalDefined": 0,
}
