ALL_CHARACTER_PROPERTIES = {
    "∑": {
        "character": "∑",
        "name": "N-ARY SUMMATION",
        "codepoint": "U+2211",
        "uriEncoded": "%E2%88%91",
        "block": "Mathematical Operators",
        "plane": "BMP",
        "age": "1.1",
        "generalCategory": "Math Symbol (Sm)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#8721;", "&#x2211;", "&sum;"],
        "utf8": "0xE2 0x88 0x91",
        "utf8HexBytes": ["E2", "88", "91"],
        "utf8DecBytes": ["226", "136", "145"],
        "utf16": "0x2211",
        "utf16HexBytes": ["2211"],
        "utf16DecBytes": ["8721"],
        "utf32": "0x00002211",
        "utf32HexBytes": ["00002211"],
        "utf32DecBytes": ["8721"],
        "bidirectionalClass": "Other Neutral (ON)",
        "bidirectionalIsMirrored": True,
        "bidirectionalMirroringGlyph": "",
        "bidirectionalControl": False,
        "pairedBracketType": "None (n)",
        "pairedBracketProperty": "∑ (U+2211)",
        "decompositionType": "None (none)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "numericType": "None (None)",
        "numericValue": "NaN",
        "numericValueParsed": None,
        "joiningType": "Non Joining (U)",
        "joiningGroup": "No_Joining_Group",
        "joiningControl": False,
        "lineBreak": "Ambiguous (Alphabetic Or Ideographic) (AI)",
        "eastAsianWidth": "East Asian Ambiguous (A)",
        "uppercase": False,
        "lowercase": False,
        "simpleUppercaseMapping": "∑ (U+2211)",
        "simpleLowercaseMapping": "∑ (U+2211)",
        "simpleTitlecaseMapping": "∑ (U+2211)",
        "simpleCaseFolding": "∑ (U+2211)",
        "script": "Common (Zyyy)",
        "scriptExtension": ["Common (Zyyy)"],
        "hangulSyllableType": "Not Applicable (NA)",
        "indicSyllabicCategory": "Other",
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "dash": False,
        "hyphen": False,
        "quotationMark": False,
        "terminalPunctuation": False,
        "sentenceTerminal": False,
        "diacritic": False,
        "extender": False,
        "softDotted": False,
        "alphabetic": False,
        "math": True,
        "hexDigit": False,
        "asciiHexDigit": False,
        "defaultIgnorableCodePoint": False,
        "logicalOrderException": False,
        "prependedConcatenationMark": False,
        "whiteSpace": False,
        "verticalOrientation": "Rotated 90 degrees clockwise (R)",
        "regionalIndicator": False,
        "emoji": False,
        "emojiPresentation": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiComponent": False,
        "extendedPictographic": False,
    },
    "ཀྵ": {
        "character": "ཀྵ",
        "name": "TIBETAN LETTER KSSA",
        "codepoint": "U+0F69",
        "uriEncoded": "%E0%BD%A9",
        "block": "Tibetan",
        "plane": "BMP",
        "age": "2.0",
        "generalCategory": "Other Letter (Lo)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#3945;", "&#xF69;"],
        "utf8": "0xE0 0xBD 0xA9",
        "utf8HexBytes": ["E0", "BD", "A9"],
        "utf8DecBytes": ["224", "189", "169"],
        "utf16": "0x0F69",
        "utf16HexBytes": ["0F69"],
        "utf16DecBytes": ["3945"],
        "utf32": "0x00000F69",
        "utf32HexBytes": ["00000F69"],
        "utf32DecBytes": ["3945"],
        "bidirectionalClass": "Left To Right (L)",
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": "",
        "bidirectionalControl": False,
        "pairedBracketType": "None (n)",
        "pairedBracketProperty": "ཀྵ (U+0F69)",
        "decompositionType": "Canonical (can)",
        "NFC_QC": "No",
        "NFD_QC": "No",
        "NFKC_QC": "No",
        "NFKD_QC": "No",
        "numericType": "None (None)",
        "numericValue": "NaN",
        "numericValueParsed": None,
        "joiningType": "Non Joining (U)",
        "joiningGroup": "No_Joining_Group",
        "joiningControl": False,
        "lineBreak": "Ordinary Alphabetic And Symbol (AL)",
        "eastAsianWidth": "Neutral Not East Asian (N)",
        "uppercase": False,
        "lowercase": False,
        "simpleUppercaseMapping": "ཀྵ (U+0F69)",
        "simpleLowercaseMapping": "ཀྵ (U+0F69)",
        "simpleTitlecaseMapping": "ཀྵ (U+0F69)",
        "simpleCaseFolding": "ཀྵ (U+0F69)",
        "script": "Tibetan (Tibt)",
        "scriptExtension": ["Tibetan (Tibt)"],
        "hangulSyllableType": "Not Applicable (NA)",
        "indicSyllabicCategory": "Consonant",
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "dash": False,
        "hyphen": False,
        "quotationMark": False,
        "terminalPunctuation": False,
        "sentenceTerminal": False,
        "diacritic": False,
        "extender": False,
        "softDotted": False,
        "alphabetic": True,
        "math": False,
        "hexDigit": False,
        "asciiHexDigit": False,
        "defaultIgnorableCodePoint": False,
        "logicalOrderException": False,
        "prependedConcatenationMark": False,
        "whiteSpace": False,
        "verticalOrientation": "Rotated 90 degrees clockwise (R)",
        "regionalIndicator": False,
        "emoji": False,
        "emojiPresentation": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiComponent": False,
        "extendedPictographic": False,
    },
    "🐍": {
        "character": "🐍",
        "name": "SNAKE",
        "codepoint": "U+1F40D",
        "uriEncoded": "%F0%9F%90%8D",
        "block": "Miscellaneous Symbols and Pictographs",
        "plane": "SMP",
        "age": "6.0",
        "generalCategory": "Other Symbol (So)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#128013;", "&#x1F40D;"],
        "utf8": "0xF0 0x9F 0x90 0x8D",
        "utf8HexBytes": ["F0", "9F", "90", "8D"],
        "utf8DecBytes": ["240", "159", "144", "141"],
        "utf16": "0xD83D 0xDC0D",
        "utf16HexBytes": ["D83D", "DC0D"],
        "utf16DecBytes": ["55357", "56333"],
        "utf32": "0x0001F40D",
        "utf32HexBytes": ["0001F40D"],
        "utf32DecBytes": ["128013"],
        "bidirectionalClass": "Other Neutral (ON)",
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": "",
        "bidirectionalControl": False,
        "pairedBracketType": "None (n)",
        "pairedBracketProperty": "🐍 (U+1F40D)",
        "decompositionType": "None (none)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "numericType": "None (None)",
        "numericValue": "NaN",
        "numericValueParsed": None,
        "joiningType": "Non Joining (U)",
        "joiningGroup": "No_Joining_Group",
        "joiningControl": False,
        "lineBreak": "Ideographic (ID)",
        "eastAsianWidth": "East Asian Wide (W)",
        "uppercase": False,
        "lowercase": False,
        "simpleUppercaseMapping": "🐍 (U+1F40D)",
        "simpleLowercaseMapping": "🐍 (U+1F40D)",
        "simpleTitlecaseMapping": "🐍 (U+1F40D)",
        "simpleCaseFolding": "🐍 (U+1F40D)",
        "script": "Common (Zyyy)",
        "scriptExtension": ["Common (Zyyy)"],
        "hangulSyllableType": "Not Applicable (NA)",
        "indicSyllabicCategory": "Other",
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "dash": False,
        "hyphen": False,
        "quotationMark": False,
        "terminalPunctuation": False,
        "sentenceTerminal": False,
        "diacritic": False,
        "extender": False,
        "softDotted": False,
        "alphabetic": False,
        "math": False,
        "hexDigit": False,
        "asciiHexDigit": False,
        "defaultIgnorableCodePoint": False,
        "logicalOrderException": False,
        "prependedConcatenationMark": False,
        "whiteSpace": False,
        "verticalOrientation": "Upright (U)",
        "regionalIndicator": False,
        "emoji": True,
        "emojiPresentation": True,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiComponent": False,
        "extendedPictographic": True,
    },
}
