class Encoder:
    "Encode strings to bytes-like and decode bytes-like to strings"

    def __init__(self, encoding: str, encoding_errors: str, decode_responses: bool) -> None: ...
    def encode(self, value: str) -> bytes: ...
    def decode(self, value: bytes) -> str: ...
