from app.schemas.enums import CharPropertyGroup

CHARACTER_PROPERTIES = {
    "\x17": {
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "age": "1.1",
        "bidirectionalClass": "Boundary Neutral (BN)",
        "block": "Basic Latin",
        "character": "␗",
        "codepoint": "U+0017",
        "combiningClass": "Not Reordered (0)",
        "eastAsianWidth": "Neutral Not East Asian (N)",
        "generalCategory": "Control (Cc)",
        "htmlEntities": ["&#23;", "&#x17;"],
        "lineBreak": "Attached Characters And Combining Marks (CM)",
        "name": "<control-0017> END OF TRANSMISSION BLOCK (ETB)",
        "plane": "BMP",
        "script": "Common (Zyyy)",
        "scriptExtensions": ["Common (Zyyy)"],
        "uriEncoded": "%17",
        "utf16": "0x0017",
        "utf16DecBytes": ["23"],
        "utf16HexBytes": ["0017"],
        "utf32": "0x00000017",
        "utf32DecBytes": ["23"],
        "utf32HexBytes": ["00000017"],
        "utf8": "0x17",
        "utf8DecBytes": ["23"],
        "utf8HexBytes": ["17"],
        "verticalOrientation": "Rotated 90 degrees clockwise (R)",
    },
    "(": {
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "age": "1.1",
        "bidirectionalClass": "Other Neutral (ON)",
        "bidirectionalIsMirrored": True,
        "bidirectionalMirroringGlyph": ") (U+0029 RIGHT PARENTHESIS)",
        "block": "Basic Latin",
        "character": "(",
        "codepoint": "U+0028",
        "combiningClass": "Not Reordered (0)",
        "eastAsianWidth": "East Asian Narrow (Na)",
        "generalCategory": "Open Punctuation (Ps)",
        "htmlEntities": ["&#40;", "&#x28;", "&lpar;"],
        "lineBreak": "Opening Punctuation (OP)",
        "name": "LEFT PARENTHESIS",
        "pairedBracketProperty": ") (U+0029 RIGHT PARENTHESIS)",
        "pairedBracketType": "Open (o)",
        "plane": "BMP",
        "script": "Common (Zyyy)",
        "scriptExtensions": ["Common (Zyyy)"],
        "uriEncoded": "%28",
        "utf16": "0x0028",
        "utf16DecBytes": ["40"],
        "utf16HexBytes": ["0028"],
        "utf32": "0x00000028",
        "utf32DecBytes": ["40"],
        "utf32HexBytes": ["00000028"],
        "utf8": "0x28",
        "utf8DecBytes": ["40"],
        "utf8HexBytes": ["28"],
        "verticalOrientation": "Rotated 90 degrees clockwise (R)",
    },
    "∑": {
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "age": "1.1",
        "bidirectionalClass": "Other Neutral (ON)",
        "bidirectionalIsMirrored": True,
        "bidirectionalMirroringGlyph": "∑ (U+2211 N-ARY SUMMATION)",
        "block": "Mathematical Operators",
        "character": "∑",
        "codepoint": "U+2211",
        "combiningClass": "Not Reordered (0)",
        "eastAsianWidth": "East Asian Ambiguous (A)",
        "generalCategory": "Math Symbol (Sm)",
        "htmlEntities": ["&#8721;", "&#x2211;", "&sum;"],
        "lineBreak": "Ambiguous (Alphabetic Or Ideographic) (AI)",
        "math": True,
        "name": "N-ARY SUMMATION",
        "plane": "BMP",
        "script": "Common (Zyyy)",
        "scriptExtensions": ["Common (Zyyy)"],
        "uriEncoded": "%E2%88%91",
        "utf16": "0x2211",
        "utf16DecBytes": ["8721"],
        "utf16HexBytes": ["2211"],
        "utf32": "0x00002211",
        "utf32DecBytes": ["8721"],
        "utf32HexBytes": ["00002211"],
        "utf8": "0xE2 0x88 0x91",
        "utf8DecBytes": ["226", "136", "145"],
        "utf8HexBytes": ["E2", "88", "91"],
        "verticalOrientation": "Rotated 90 degrees clockwise (R)",
    },
    "㑢": {
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "age": "3.0",
        "alphabetic": True,
        "bidirectionalClass": "Left To Right (L)",
        "block": "CJK Unified Ideographs Extension A",
        "cantonese": "koek3",
        "character": "㑢",
        "codepoint": "U+3462",
        "combiningClass": "Not Reordered (0)",
        "eastAsianWidth": "East Asian Wide (W)",
        "generalCategory": "Other Letter (Lo)",
        "htmlEntities": ["&#13410;", "&#x3462;"],
        "ideographic": True,
        "lineBreak": "Ideographic (ID)",
        "name": "CJK UNIFIED IDEOGRAPH-3462",
        "plane": "BMP",
        "rsCountUnicode": "9.7",
        "script": "Han (Hani)",
        "scriptExtensions": ["Han (Hani)"],
        "totalStrokes": "9",
        "unifiedIdeograph": True,
        "uriEncoded": "%E3%91%A2",
        "utf16": "0x3462",
        "utf16DecBytes": ["13410"],
        "utf16HexBytes": ["3462"],
        "utf32": "0x00003462",
        "utf32DecBytes": ["13410"],
        "utf32HexBytes": ["00003462"],
        "utf8": "0xE3 0x91 0xA2",
        "utf8DecBytes": ["227", "145", "162"],
        "utf8HexBytes": ["E3", "91", "A2"],
        "verticalOrientation": "Upright (U)",
    },
    "穩": {
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "age": "1.1",
        "alphabetic": True,
        "bidirectionalClass": "Left To Right (L)",
        "block": "CJK Unified Ideographs",
        "cantonese": "wan2",
        "character": "穩",
        "codepoint": "U+7A69",
        "combiningClass": "Not Reordered (0)",
        "description": "stable, firm, solid, steady",
        "eastAsianWidth": "East Asian Wide (W)",
        "generalCategory": "Other Letter (Lo)",
        "hangul": "온:0N",
        "htmlEntities": ["&#31337;", "&#x7A69;"],
        "ideoFrequency": 4,
        "ideoGradeLevel": 5,
        "ideographic": True,
        "japaneseKun": "ODAYAKA",
        "japaneseOn": "ON",
        "lineBreak": "Ideographic (ID)",
        "mandarin": "wěn",
        "name": "CJK UNIFIED IDEOGRAPH-7A69",
        "plane": "BMP",
        "rsCountKangxi": "115.14",
        "rsCountUnicode": "115.14",
        "script": "Han (Hani)",
        "scriptExtensions": ["Han (Hani)"],
        "semanticVariant": ["㒚 (U+349A CJK UNIFIED IDEOGRAPH-349A)"],
        "simplifiedVariant": ["稳 (U+7A33 CJK UNIFIED IDEOGRAPH-7A33)"],
        "specializedSemanticVariant": ["文 (U+6587 CJK UNIFIED IDEOGRAPH-6587)"],
        "totalStrokes": "19",
        "unifiedIdeograph": True,
        "uriEncoded": "%E7%A9%A9",
        "utf16": "0x7A69",
        "utf16DecBytes": ["31337"],
        "utf16HexBytes": ["7A69"],
        "utf32": "0x00007A69",
        "utf32DecBytes": ["31337"],
        "utf32HexBytes": ["00007A69"],
        "utf8": "0xE7 0xA9 0xA9",
        "utf8DecBytes": ["231", "169", "169"],
        "utf8HexBytes": ["E7", "A9", "A9"],
        "verticalOrientation": "Upright (U)",
        "vietnamese": "ủn",
    },
    "\uf800": {
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "age": "1.1",
        "bidirectionalClass": "Left To Right (L)",
        "block": "Private Use Area",
        "character": "\uf800",
        "codepoint": "U+F800",
        "combiningClass": "Not Reordered (0)",
        "eastAsianWidth": "East Asian Ambiguous (A)",
        "generalCategory": "Private Use (Co)",
        "htmlEntities": ["&#63488;", "&#xF800;"],
        "indicMatraCategory": "",
        "indicPositionalCategory": "",
        "indicSyllabicCategory": "",
        "lineBreak": "Unknown (XX)",
        "name": "<private-use-F800>",
        "pairedBracketProperty": "",
        "pairedBracketType": "None (n)",
        "plane": "BMP",
        "script": "Unknown (Zzzz)",
        "scriptExtensions": ["Unknown (Zzzz)"],
        "uriEncoded": "%EF%A0%80",
        "utf16": "0xF800",
        "utf16DecBytes": ["63488"],
        "utf16HexBytes": ["F800"],
        "utf32": "0x0000F800",
        "utf32DecBytes": ["63488"],
        "utf32HexBytes": ["0000F800"],
        "utf8": "0xEF 0xA0 0x80",
        "utf8DecBytes": ["239", "160", "128"],
        "utf8HexBytes": ["EF", "A0", "80"],
        "verticalOrientation": "Upright (U)",
    },
    "\ufffe": {
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "age": "1.1",
        "bidirectionalClass": "Left To Right (L)",
        "block": "Specials",
        "character": "\ufffe",
        "codepoint": "U+FFFE",
        "combiningClass": "Not Reordered (0)",
        "eastAsianWidth": "East Asian Ambiguous (A)",
        "generalCategory": "Unassigned (Cn)",
        "htmlEntities": ["&#65534;", "&#xFFFE;"],
        "indicMatraCategory": "",
        "indicPositionalCategory": "",
        "indicSyllabicCategory": "",
        "lineBreak": "Unknown (XX)",
        "name": "<noncharacter-FFFE>",
        "pairedBracketProperty": "",
        "pairedBracketType": "None (n)",
        "plane": "BMP",
        "script": "Unknown (Zzzz)",
        "scriptExtensions": ["Unknown (Zzzz)"],
        "uriEncoded": "%EF%BF%BE",
        "utf16": "0xFFFE",
        "utf16DecBytes": ["65534"],
        "utf16HexBytes": ["FFFE"],
        "utf32": "0x0000FFFE",
        "utf32DecBytes": ["65534"],
        "utf32HexBytes": ["0000FFFE"],
        "utf8": "0xEF 0xBF 0xBE",
        "utf8DecBytes": ["239", "191", "190"],
        "utf8HexBytes": ["EF", "BF", "BE"],
        "verticalOrientation": "Upright (U)",
    },
    "🇦": {
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "age": "6.0",
        "bidirectionalClass": "Left To Right (L)",
        "block": "Enclosed Alphanumeric Supplement",
        "character": "🇦",
        "codepoint": "U+1F1E6",
        "combiningClass": "Not Reordered (0)",
        "eastAsianWidth": "Neutral Not East Asian (N)",
        "emoji": True,
        "emojiComponent": True,
        "emojiPresentation": True,
        "generalCategory": "Other Symbol (So)",
        "htmlEntities": ["&#127462;", "&#x1F1E6;"],
        "lineBreak": "Unknown (XX)",
        "name": "REGIONAL INDICATOR SYMBOL LETTER A",
        "plane": "SMP",
        "regionalIndicator": True,
        "script": "Common (Zyyy)",
        "scriptExtensions": ["Common (Zyyy)"],
        "uriEncoded": "%F0%9F%87%A6",
        "utf16": "0xD83C 0xDDE6",
        "utf16DecBytes": ["55356", "56806"],
        "utf16HexBytes": ["D83C", "DDE6"],
        "utf32": "0x0001F1E6",
        "utf32DecBytes": ["127462"],
        "utf32HexBytes": ["0001F1E6"],
        "utf8": "0xF0 0x9F 0x87 0xA6",
        "utf8DecBytes": ["240", "159", "135", "166"],
        "utf8HexBytes": ["F0", "9F", "87", "A6"],
        "verticalOrientation": "Upright (U)",
    },
    "🐍": {
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "age": "6.0",
        "bidirectionalClass": "Other Neutral (ON)",
        "block": "Miscellaneous Symbols and Pictographs",
        "character": "🐍",
        "codepoint": "U+1F40D",
        "combiningClass": "Not Reordered (0)",
        "eastAsianWidth": "East Asian Wide (W)",
        "emoji": True,
        "emojiPresentation": True,
        "extendedPictographic": True,
        "generalCategory": "Other Symbol (So)",
        "htmlEntities": ["&#128013;", "&#x1F40D;"],
        "lineBreak": "Ideographic (ID)",
        "name": "SNAKE",
        "plane": "SMP",
        "script": "Common (Zyyy)",
        "scriptExtensions": ["Common (Zyyy)"],
        "uriEncoded": "%F0%9F%90%8D",
        "utf16": "0xD83D 0xDC0D",
        "utf16DecBytes": ["55357", "56333"],
        "utf16HexBytes": ["D83D", "DC0D"],
        "utf32": "0x0001F40D",
        "utf32DecBytes": ["128013"],
        "utf32HexBytes": ["0001F40D"],
        "utf8": "0xF0 0x9F 0x90 0x8D",
        "utf8DecBytes": ["240", "159", "144", "141"],
        "utf8HexBytes": ["F0", "9F", "90", "8D"],
        "verticalOrientation": "Upright (U)",
    },
}

VERBOSE_CHARACTER_PROPERTIES = {
    "\x17": {
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "age": "1.1",
        "alphabetic": False,
        "asciiHexDigit": False,
        "bidirectionalClass": "Boundary Neutral (BN)",
        "bidirectionalControl": False,
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": "\x17 (U+0017 <control-0017> END OF TRANSMISSION BLOCK (ETB))",
        "block": "Basic Latin",
        "character": "␗",
        "codepoint": "U+0017",
        "combiningClass": "Not Reordered (0)",
        "dash": False,
        "decompositionType": "None (none)",
        "defaultIgnorableCodePoint": False,
        "diacritic": False,
        "eastAsianWidth": "Neutral Not East Asian (N)",
        "emoji": False,
        "emojiComponent": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiPresentation": False,
        "equivalentUnifiedIdeograph": "",
        "extendedPictographic": False,
        "extender": False,
        "generalCategory": "Control (Cc)",
        "hangulSyllableType": "Not Applicable (NA)",
        "hexDigit": False,
        "htmlEntities": ["&#23;", "&#x17;"],
        "hyphen": False,
        "ideographic": False,
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "indicSyllabicCategory": "Other",
        "joiningControl": False,
        "joiningGroup": "No_Joining_Group",
        "joiningType": "Non Joining (U)",
        "lineBreak": "Attached Characters And Combining Marks (CM)",
        "logicalOrderException": False,
        "lowercase": False,
        "math": False,
        "name": "<control-0017> END OF TRANSMISSION BLOCK (ETB)",
        "numericType": "None (None)",
        "numericValue": "NaN",
        "numericValueParsed": None,
        "pairedBracketProperty": "\x17 (U+0017 <control-0017> END OF " "TRANSMISSION BLOCK (ETB))",
        "pairedBracketType": "None (n)",
        "plane": "BMP",
        "prependedConcatenationMark": False,
        "quotationMark": False,
        "radical": False,
        "regionalIndicator": False,
        "script": "Common (Zyyy)",
        "scriptExtensions": ["Common (Zyyy)"],
        "sentenceTerminal": False,
        "simpleCaseFolding": "\x17 (U+0017 <control-0017> END OF " "TRANSMISSION BLOCK (ETB))",
        "simpleLowercaseMapping": "\x17 (U+0017 <control-0017> END OF " "TRANSMISSION BLOCK (ETB))",
        "simpleTitlecaseMapping": "\x17 (U+0017 <control-0017> END OF " "TRANSMISSION BLOCK (ETB))",
        "simpleUppercaseMapping": "\x17 (U+0017 <control-0017> END OF " "TRANSMISSION BLOCK (ETB))",
        "softDotted": False,
        "terminalPunctuation": False,
        "unifiedIdeograph": False,
        "uppercase": False,
        "uriEncoded": "%17",
        "utf16": "0x0017",
        "utf16DecBytes": ["23"],
        "utf16HexBytes": ["0017"],
        "utf32": "0x00000017",
        "utf32DecBytes": ["23"],
        "utf32HexBytes": ["00000017"],
        "utf8": "0x17",
        "utf8DecBytes": ["23"],
        "utf8HexBytes": ["17"],
        "verticalOrientation": "Rotated 90 degrees clockwise (R)",
        "whiteSpace": False,
    },
    "(": {
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "age": "1.1",
        "alphabetic": False,
        "asciiHexDigit": False,
        "bidirectionalClass": "Other Neutral (ON)",
        "bidirectionalControl": False,
        "bidirectionalIsMirrored": True,
        "bidirectionalMirroringGlyph": ") (U+0029 RIGHT PARENTHESIS)",
        "block": "Basic Latin",
        "character": "(",
        "codepoint": "U+0028",
        "combiningClass": "Not Reordered (0)",
        "dash": False,
        "decompositionType": "None (none)",
        "defaultIgnorableCodePoint": False,
        "diacritic": False,
        "eastAsianWidth": "East Asian Narrow (Na)",
        "emoji": False,
        "emojiComponent": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiPresentation": False,
        "equivalentUnifiedIdeograph": "",
        "extendedPictographic": False,
        "extender": False,
        "generalCategory": "Open Punctuation (Ps)",
        "hangulSyllableType": "Not Applicable (NA)",
        "hexDigit": False,
        "htmlEntities": ["&#40;", "&#x28;", "&lpar;"],
        "hyphen": False,
        "ideographic": False,
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "indicSyllabicCategory": "Other",
        "joiningControl": False,
        "joiningGroup": "No_Joining_Group",
        "joiningType": "Non Joining (U)",
        "lineBreak": "Opening Punctuation (OP)",
        "logicalOrderException": False,
        "lowercase": False,
        "math": False,
        "name": "LEFT PARENTHESIS",
        "numericType": "None (None)",
        "numericValue": "NaN",
        "numericValueParsed": None,
        "pairedBracketProperty": ") (U+0029 RIGHT PARENTHESIS)",
        "pairedBracketType": "Open (o)",
        "plane": "BMP",
        "prependedConcatenationMark": False,
        "quotationMark": False,
        "radical": False,
        "regionalIndicator": False,
        "script": "Common (Zyyy)",
        "scriptExtensions": ["Common (Zyyy)"],
        "sentenceTerminal": False,
        "simpleCaseFolding": "( (U+0028 LEFT PARENTHESIS)",
        "simpleLowercaseMapping": "( (U+0028 LEFT PARENTHESIS)",
        "simpleTitlecaseMapping": "( (U+0028 LEFT PARENTHESIS)",
        "simpleUppercaseMapping": "( (U+0028 LEFT PARENTHESIS)",
        "softDotted": False,
        "terminalPunctuation": False,
        "unifiedIdeograph": False,
        "uppercase": False,
        "uriEncoded": "%28",
        "utf16": "0x0028",
        "utf16DecBytes": ["40"],
        "utf16HexBytes": ["0028"],
        "utf32": "0x00000028",
        "utf32DecBytes": ["40"],
        "utf32HexBytes": ["00000028"],
        "utf8": "0x28",
        "utf8DecBytes": ["40"],
        "utf8HexBytes": ["28"],
        "verticalOrientation": "Rotated 90 degrees clockwise (R)",
        "whiteSpace": False,
    },
    "∑": {
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "age": "1.1",
        "alphabetic": False,
        "asciiHexDigit": False,
        "bidirectionalClass": "Other Neutral (ON)",
        "bidirectionalControl": False,
        "bidirectionalIsMirrored": True,
        "bidirectionalMirroringGlyph": "∑ (U+2211 N-ARY SUMMATION)",
        "block": "Mathematical Operators",
        "character": "∑",
        "codepoint": "U+2211",
        "combiningClass": "Not Reordered (0)",
        "dash": False,
        "decompositionType": "None (none)",
        "defaultIgnorableCodePoint": False,
        "diacritic": False,
        "eastAsianWidth": "East Asian Ambiguous (A)",
        "emoji": False,
        "emojiComponent": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiPresentation": False,
        "equivalentUnifiedIdeograph": "",
        "extendedPictographic": False,
        "extender": False,
        "generalCategory": "Math Symbol (Sm)",
        "hangulSyllableType": "Not Applicable (NA)",
        "hexDigit": False,
        "htmlEntities": ["&#8721;", "&#x2211;", "&sum;"],
        "hyphen": False,
        "ideographic": False,
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "indicSyllabicCategory": "Other",
        "joiningControl": False,
        "joiningGroup": "No_Joining_Group",
        "joiningType": "Non Joining (U)",
        "lineBreak": "Ambiguous (Alphabetic Or Ideographic) (AI)",
        "logicalOrderException": False,
        "lowercase": False,
        "math": True,
        "name": "N-ARY SUMMATION",
        "numericType": "None (None)",
        "numericValue": "NaN",
        "numericValueParsed": None,
        "pairedBracketProperty": "∑ (U+2211 N-ARY SUMMATION)",
        "pairedBracketType": "None (n)",
        "plane": "BMP",
        "prependedConcatenationMark": False,
        "quotationMark": False,
        "radical": False,
        "regionalIndicator": False,
        "script": "Common (Zyyy)",
        "scriptExtensions": ["Common (Zyyy)"],
        "sentenceTerminal": False,
        "simpleCaseFolding": "∑ (U+2211 N-ARY SUMMATION)",
        "simpleLowercaseMapping": "∑ (U+2211 N-ARY SUMMATION)",
        "simpleTitlecaseMapping": "∑ (U+2211 N-ARY SUMMATION)",
        "simpleUppercaseMapping": "∑ (U+2211 N-ARY SUMMATION)",
        "softDotted": False,
        "terminalPunctuation": False,
        "unifiedIdeograph": False,
        "uppercase": False,
        "uriEncoded": "%E2%88%91",
        "utf16": "0x2211",
        "utf16DecBytes": ["8721"],
        "utf16HexBytes": ["2211"],
        "utf32": "0x00002211",
        "utf32DecBytes": ["8721"],
        "utf32HexBytes": ["00002211"],
        "utf8": "0xE2 0x88 0x91",
        "utf8DecBytes": ["226", "136", "145"],
        "utf8HexBytes": ["E2", "88", "91"],
        "verticalOrientation": "Rotated 90 degrees clockwise (R)",
        "whiteSpace": False,
    },
    "㑢": {
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "accountingNumeric": "0",
        "age": "3.0",
        "alphabetic": True,
        "asciiHexDigit": False,
        "bidirectionalClass": "Left To Right (L)",
        "bidirectionalControl": False,
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": "㑢 (U+3462 CJK UNIFIED IDEOGRAPH-3462)",
        "block": "CJK Unified Ideographs Extension A",
        "cantonese": "koek3",
        "character": "㑢",
        "codepoint": "U+3462",
        "combiningClass": "Not Reordered (0)",
        "compatibilityVariant": [""],
        "dash": False,
        "decompositionType": "None (none)",
        "defaultIgnorableCodePoint": False,
        "description": "",
        "diacritic": False,
        "eastAsianWidth": "East Asian Wide (W)",
        "emoji": False,
        "emojiComponent": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiPresentation": False,
        "equivalentUnifiedIdeograph": "",
        "extendedPictographic": False,
        "extender": False,
        "generalCategory": "Other Letter (Lo)",
        "hangul": "",
        "hangulSyllableType": "Not Applicable (NA)",
        "hexDigit": False,
        "htmlEntities": ["&#13410;", "&#x3462;"],
        "hyphen": False,
        "ideoFrequency": 0,
        "ideoGradeLevel": 0,
        "ideographic": True,
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "indicSyllabicCategory": "Other",
        "japaneseKun": "",
        "japaneseOn": "",
        "joiningControl": False,
        "joiningGroup": "No_Joining_Group",
        "joiningType": "Non Joining (U)",
        "lineBreak": "Ideographic (ID)",
        "logicalOrderException": False,
        "lowercase": False,
        "mandarin": "",
        "math": False,
        "name": "CJK UNIFIED IDEOGRAPH-3462",
        "numericType": "None (None)",
        "numericValue": "NaN",
        "numericValueParsed": None,
        "otherNumeric": "0",
        "pairedBracketProperty": "㑢 (U+3462 CJK UNIFIED IDEOGRAPH-3462)",
        "pairedBracketType": "None (n)",
        "plane": "BMP",
        "prependedConcatenationMark": False,
        "primaryNumeric": "0",
        "quotationMark": False,
        "radical": False,
        "regionalIndicator": False,
        "rsCountKangxi": "",
        "rsCountUnicode": "9.7",
        "script": "Han (Hani)",
        "scriptExtensions": ["Han (Hani)"],
        "semanticVariant": [""],
        "sentenceTerminal": False,
        "simpleCaseFolding": "㑢 (U+3462 CJK UNIFIED IDEOGRAPH-3462)",
        "simpleLowercaseMapping": "㑢 (U+3462 CJK UNIFIED IDEOGRAPH-3462)",
        "simpleTitlecaseMapping": "㑢 (U+3462 CJK UNIFIED IDEOGRAPH-3462)",
        "simpleUppercaseMapping": "㑢 (U+3462 CJK UNIFIED IDEOGRAPH-3462)",
        "simplifiedVariant": [""],
        "softDotted": False,
        "specializedSemanticVariant": [""],
        "spoofingVariant": [""],
        "terminalPunctuation": False,
        "totalStrokes": "9",
        "traditionalVariant": [""],
        "unifiedIdeograph": True,
        "uppercase": False,
        "uriEncoded": "%E3%91%A2",
        "utf16": "0x3462",
        "utf16DecBytes": ["13410"],
        "utf16HexBytes": ["3462"],
        "utf32": "0x00003462",
        "utf32DecBytes": ["13410"],
        "utf32HexBytes": ["00003462"],
        "utf8": "0xE3 0x91 0xA2",
        "utf8DecBytes": ["227", "145", "162"],
        "utf8HexBytes": ["E3", "91", "A2"],
        "verticalOrientation": "Upright (U)",
        "vietnamese": "",
        "whiteSpace": False,
        "zVariant": [""],
    },
    "穩": {
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "accountingNumeric": "0",
        "age": "1.1",
        "alphabetic": True,
        "asciiHexDigit": False,
        "bidirectionalClass": "Left To Right (L)",
        "bidirectionalControl": False,
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": "穩 (U+7A69 CJK UNIFIED IDEOGRAPH-7A69)",
        "block": "CJK Unified Ideographs",
        "cantonese": "wan2",
        "character": "穩",
        "codepoint": "U+7A69",
        "combiningClass": "Not Reordered (0)",
        "compatibilityVariant": [""],
        "dash": False,
        "decompositionType": "None (none)",
        "defaultIgnorableCodePoint": False,
        "description": "stable, firm, solid, steady",
        "diacritic": False,
        "eastAsianWidth": "East Asian Wide (W)",
        "emoji": False,
        "emojiComponent": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiPresentation": False,
        "equivalentUnifiedIdeograph": "",
        "extendedPictographic": False,
        "extender": False,
        "generalCategory": "Other Letter (Lo)",
        "hangul": "온:0N",
        "hangulSyllableType": "Not Applicable (NA)",
        "hexDigit": False,
        "htmlEntities": ["&#31337;", "&#x7A69;"],
        "hyphen": False,
        "ideoFrequency": 4,
        "ideoGradeLevel": 5,
        "ideographic": True,
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "indicSyllabicCategory": "Other",
        "japaneseKun": "ODAYAKA",
        "japaneseOn": "ON",
        "joiningControl": False,
        "joiningGroup": "No_Joining_Group",
        "joiningType": "Non Joining (U)",
        "lineBreak": "Ideographic (ID)",
        "logicalOrderException": False,
        "lowercase": False,
        "mandarin": "wěn",
        "math": False,
        "name": "CJK UNIFIED IDEOGRAPH-7A69",
        "numericType": "None (None)",
        "numericValue": "NaN",
        "numericValueParsed": None,
        "otherNumeric": "0",
        "pairedBracketProperty": "穩 (U+7A69 CJK UNIFIED IDEOGRAPH-7A69)",
        "pairedBracketType": "None (n)",
        "plane": "BMP",
        "prependedConcatenationMark": False,
        "primaryNumeric": "0",
        "quotationMark": False,
        "radical": False,
        "regionalIndicator": False,
        "rsCountKangxi": "115.14",
        "rsCountUnicode": "115.14",
        "script": "Han (Hani)",
        "scriptExtensions": ["Han (Hani)"],
        "semanticVariant": ["㒚 (U+349A CJK UNIFIED IDEOGRAPH-349A)"],
        "sentenceTerminal": False,
        "simpleCaseFolding": "穩 (U+7A69 CJK UNIFIED IDEOGRAPH-7A69)",
        "simpleLowercaseMapping": "穩 (U+7A69 CJK UNIFIED IDEOGRAPH-7A69)",
        "simpleTitlecaseMapping": "穩 (U+7A69 CJK UNIFIED IDEOGRAPH-7A69)",
        "simpleUppercaseMapping": "穩 (U+7A69 CJK UNIFIED IDEOGRAPH-7A69)",
        "simplifiedVariant": ["稳 (U+7A33 CJK UNIFIED IDEOGRAPH-7A33)"],
        "softDotted": False,
        "specializedSemanticVariant": ["文 (U+6587 CJK UNIFIED IDEOGRAPH-6587)"],
        "spoofingVariant": [""],
        "terminalPunctuation": False,
        "totalStrokes": "19",
        "traditionalVariant": [""],
        "unifiedIdeograph": True,
        "uppercase": False,
        "uriEncoded": "%E7%A9%A9",
        "utf16": "0x7A69",
        "utf16DecBytes": ["31337"],
        "utf16HexBytes": ["7A69"],
        "utf32": "0x00007A69",
        "utf32DecBytes": ["31337"],
        "utf32HexBytes": ["00007A69"],
        "utf8": "0xE7 0xA9 0xA9",
        "utf8DecBytes": ["231", "169", "169"],
        "utf8HexBytes": ["E7", "A9", "A9"],
        "verticalOrientation": "Upright (U)",
        "vietnamese": "ủn",
        "whiteSpace": False,
        "zVariant": [""],
    },
    "\uf800": {
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "age": "1.1",
        "alphabetic": False,
        "asciiHexDigit": False,
        "bidirectionalClass": "Left To Right (L)",
        "bidirectionalControl": False,
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": "\uf800 (U+F800 <private-use-F800>)",
        "block": "Private Use Area",
        "character": "\uf800",
        "codepoint": "U+F800",
        "combiningClass": "Not Reordered (0)",
        "dash": False,
        "decompositionType": "None (none)",
        "defaultIgnorableCodePoint": False,
        "diacritic": False,
        "eastAsianWidth": "East Asian Ambiguous (A)",
        "emoji": False,
        "emojiComponent": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiPresentation": False,
        "equivalentUnifiedIdeograph": "",
        "extendedPictographic": False,
        "extender": False,
        "generalCategory": "Private Use (Co)",
        "hangulSyllableType": "Not Applicable (NA)",
        "hexDigit": False,
        "htmlEntities": ["&#63488;", "&#xF800;"],
        "hyphen": False,
        "ideographic": False,
        "indicMatraCategory": "",
        "indicPositionalCategory": "",
        "indicSyllabicCategory": "",
        "joiningControl": False,
        "joiningGroup": "",
        "joiningType": "Non Joining (U)",
        "lineBreak": "Unknown (XX)",
        "logicalOrderException": False,
        "lowercase": False,
        "math": False,
        "name": "<private-use-F800>",
        "numericType": "None (None)",
        "numericValue": "",
        "numericValueParsed": 0.0,
        "pairedBracketProperty": "",
        "pairedBracketType": "None (n)",
        "plane": "BMP",
        "prependedConcatenationMark": False,
        "quotationMark": False,
        "radical": False,
        "regionalIndicator": False,
        "script": "Unknown (Zzzz)",
        "scriptExtensions": ["Unknown (Zzzz)"],
        "sentenceTerminal": False,
        "simpleCaseFolding": "",
        "simpleLowercaseMapping": "",
        "simpleTitlecaseMapping": "",
        "simpleUppercaseMapping": "",
        "softDotted": False,
        "terminalPunctuation": False,
        "unifiedIdeograph": False,
        "uppercase": False,
        "uriEncoded": "%EF%A0%80",
        "utf16": "0xF800",
        "utf16DecBytes": ["63488"],
        "utf16HexBytes": ["F800"],
        "utf32": "0x0000F800",
        "utf32DecBytes": ["63488"],
        "utf32HexBytes": ["0000F800"],
        "utf8": "0xEF 0xA0 0x80",
        "utf8DecBytes": ["239", "160", "128"],
        "utf8HexBytes": ["EF", "A0", "80"],
        "verticalOrientation": "Upright (U)",
        "whiteSpace": False,
    },
    "\ufffe": {
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "age": "1.1",
        "alphabetic": False,
        "asciiHexDigit": False,
        "bidirectionalClass": "Left To Right (L)",
        "bidirectionalControl": False,
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": "\ufffe (U+FFFE <noncharacter-FFFE>)",
        "block": "Specials",
        "character": "\ufffe",
        "codepoint": "U+FFFE",
        "combiningClass": "Not Reordered (0)",
        "dash": False,
        "decompositionType": "None (none)",
        "defaultIgnorableCodePoint": False,
        "diacritic": False,
        "eastAsianWidth": "East Asian Ambiguous (A)",
        "emoji": False,
        "emojiComponent": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiPresentation": False,
        "equivalentUnifiedIdeograph": "",
        "extendedPictographic": False,
        "extender": False,
        "generalCategory": "Unassigned (Cn)",
        "hangulSyllableType": "Not Applicable (NA)",
        "hexDigit": False,
        "htmlEntities": ["&#65534;", "&#xFFFE;"],
        "hyphen": False,
        "ideographic": False,
        "indicMatraCategory": "",
        "indicPositionalCategory": "",
        "indicSyllabicCategory": "",
        "joiningControl": False,
        "joiningGroup": "",
        "joiningType": "Non Joining (U)",
        "lineBreak": "Unknown (XX)",
        "logicalOrderException": False,
        "lowercase": False,
        "math": False,
        "name": "<noncharacter-FFFE>",
        "numericType": "None (None)",
        "numericValue": "",
        "numericValueParsed": 0.0,
        "pairedBracketProperty": "",
        "pairedBracketType": "None (n)",
        "plane": "BMP",
        "prependedConcatenationMark": False,
        "quotationMark": False,
        "radical": False,
        "regionalIndicator": False,
        "script": "Unknown (Zzzz)",
        "scriptExtensions": ["Unknown (Zzzz)"],
        "sentenceTerminal": False,
        "simpleCaseFolding": "",
        "simpleLowercaseMapping": "",
        "simpleTitlecaseMapping": "",
        "simpleUppercaseMapping": "",
        "softDotted": False,
        "terminalPunctuation": False,
        "unifiedIdeograph": False,
        "uppercase": False,
        "uriEncoded": "%EF%BF%BE",
        "utf16": "0xFFFE",
        "utf16DecBytes": ["65534"],
        "utf16HexBytes": ["FFFE"],
        "utf32": "0x0000FFFE",
        "utf32DecBytes": ["65534"],
        "utf32HexBytes": ["0000FFFE"],
        "utf8": "0xEF 0xBF 0xBE",
        "utf8DecBytes": ["239", "191", "190"],
        "utf8HexBytes": ["EF", "BF", "BE"],
        "verticalOrientation": "Upright (U)",
        "whiteSpace": False,
    },
    "🇦": {
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "age": "6.0",
        "alphabetic": False,
        "asciiHexDigit": False,
        "bidirectionalClass": "Left To Right (L)",
        "bidirectionalControl": False,
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": "🇦 (U+1F1E6 REGIONAL INDICATOR SYMBOL LETTER A)",
        "block": "Enclosed Alphanumeric Supplement",
        "character": "🇦",
        "codepoint": "U+1F1E6",
        "combiningClass": "Not Reordered (0)",
        "dash": False,
        "decompositionType": "None (none)",
        "defaultIgnorableCodePoint": False,
        "diacritic": False,
        "eastAsianWidth": "Neutral Not East Asian (N)",
        "emoji": True,
        "emojiComponent": True,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiPresentation": True,
        "equivalentUnifiedIdeograph": "",
        "extendedPictographic": False,
        "extender": False,
        "generalCategory": "Other Symbol (So)",
        "hangulSyllableType": "Not Applicable (NA)",
        "hexDigit": False,
        "htmlEntities": ["&#127462;", "&#x1F1E6;"],
        "hyphen": False,
        "ideographic": False,
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "indicSyllabicCategory": "Other",
        "joiningControl": False,
        "joiningGroup": "No_Joining_Group",
        "joiningType": "Non Joining (U)",
        "lineBreak": "Unknown (XX)",
        "logicalOrderException": False,
        "lowercase": False,
        "math": False,
        "name": "REGIONAL INDICATOR SYMBOL LETTER A",
        "numericType": "None (None)",
        "numericValue": "NaN",
        "numericValueParsed": None,
        "pairedBracketProperty": "🇦 (U+1F1E6 REGIONAL INDICATOR SYMBOL LETTER " "A)",
        "pairedBracketType": "None (n)",
        "plane": "SMP",
        "prependedConcatenationMark": False,
        "quotationMark": False,
        "radical": False,
        "regionalIndicator": True,
        "script": "Common (Zyyy)",
        "scriptExtensions": ["Common (Zyyy)"],
        "sentenceTerminal": False,
        "simpleCaseFolding": "🇦 (U+1F1E6 REGIONAL INDICATOR SYMBOL LETTER A)",
        "simpleLowercaseMapping": "🇦 (U+1F1E6 REGIONAL INDICATOR SYMBOL LETTER " "A)",
        "simpleTitlecaseMapping": "🇦 (U+1F1E6 REGIONAL INDICATOR SYMBOL LETTER " "A)",
        "simpleUppercaseMapping": "🇦 (U+1F1E6 REGIONAL INDICATOR SYMBOL LETTER " "A)",
        "softDotted": False,
        "terminalPunctuation": False,
        "unifiedIdeograph": False,
        "uppercase": False,
        "uriEncoded": "%F0%9F%87%A6",
        "utf16": "0xD83C 0xDDE6",
        "utf16DecBytes": ["55356", "56806"],
        "utf16HexBytes": ["D83C", "DDE6"],
        "utf32": "0x0001F1E6",
        "utf32DecBytes": ["127462"],
        "utf32HexBytes": ["0001F1E6"],
        "utf8": "0xF0 0x9F 0x87 0xA6",
        "utf8DecBytes": ["240", "159", "135", "166"],
        "utf8HexBytes": ["F0", "9F", "87", "A6"],
        "verticalOrientation": "Upright (U)",
        "whiteSpace": False,
    },
    "🐍": {
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "age": "6.0",
        "alphabetic": False,
        "asciiHexDigit": False,
        "bidirectionalClass": "Other Neutral (ON)",
        "bidirectionalControl": False,
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": "🐍 (U+1F40D SNAKE)",
        "block": "Miscellaneous Symbols and Pictographs",
        "character": "🐍",
        "codepoint": "U+1F40D",
        "combiningClass": "Not Reordered (0)",
        "dash": False,
        "decompositionType": "None (none)",
        "defaultIgnorableCodePoint": False,
        "diacritic": False,
        "eastAsianWidth": "East Asian Wide (W)",
        "emoji": True,
        "emojiComponent": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiPresentation": True,
        "equivalentUnifiedIdeograph": "",
        "extendedPictographic": True,
        "extender": False,
        "generalCategory": "Other Symbol (So)",
        "hangulSyllableType": "Not Applicable (NA)",
        "hexDigit": False,
        "htmlEntities": ["&#128013;", "&#x1F40D;"],
        "hyphen": False,
        "ideographic": False,
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "indicSyllabicCategory": "Other",
        "joiningControl": False,
        "joiningGroup": "No_Joining_Group",
        "joiningType": "Non Joining (U)",
        "lineBreak": "Ideographic (ID)",
        "logicalOrderException": False,
        "lowercase": False,
        "math": False,
        "name": "SNAKE",
        "numericType": "None (None)",
        "numericValue": "NaN",
        "numericValueParsed": None,
        "pairedBracketProperty": "🐍 (U+1F40D SNAKE)",
        "pairedBracketType": "None (n)",
        "plane": "SMP",
        "prependedConcatenationMark": False,
        "quotationMark": False,
        "radical": False,
        "regionalIndicator": False,
        "script": "Common (Zyyy)",
        "scriptExtensions": ["Common (Zyyy)"],
        "sentenceTerminal": False,
        "simpleCaseFolding": "🐍 (U+1F40D SNAKE)",
        "simpleLowercaseMapping": "🐍 (U+1F40D SNAKE)",
        "simpleTitlecaseMapping": "🐍 (U+1F40D SNAKE)",
        "simpleUppercaseMapping": "🐍 (U+1F40D SNAKE)",
        "softDotted": False,
        "terminalPunctuation": False,
        "unifiedIdeograph": False,
        "uppercase": False,
        "uriEncoded": "%F0%9F%90%8D",
        "utf16": "0xD83D 0xDC0D",
        "utf16DecBytes": ["55357", "56333"],
        "utf16HexBytes": ["D83D", "DC0D"],
        "utf32": "0x0001F40D",
        "utf32DecBytes": ["128013"],
        "utf32HexBytes": ["0001F40D"],
        "utf8": "0xF0 0x9F 0x90 0x8D",
        "utf8DecBytes": ["240", "159", "144", "141"],
        "utf8HexBytes": ["F0", "9F", "90", "8D"],
        "verticalOrientation": "Upright (U)",
        "whiteSpace": False,
    },
}


def get_all_prop_names():
    prop_names = [prop_group.normalized for prop_group in CharPropertyGroup if prop_group != CharPropertyGroup.NONE]
    prop_aliases = [prop_group.short_alias for prop_group in CharPropertyGroup if prop_group.has_alias]
    return list(set(prop_names + prop_aliases))


ALL_PROP_GROUP_NAMES = get_all_prop_names()

INVALID_PROP_GROUP_NAMES = {
    "detail": "3 values provided for the 'show_props' parameter are invalid: ['foo', 'bar', 'baz']"
}
