from app.schemas.enums.property_group import CharPropertyGroup

ALL_CHARACTER_PROPERTIES = {
    "∑": {
        "character": "∑",
        "name": "N-ARY SUMMATION",
        "codepoint": "U+2211",
        "uriEncoded": "%E2%88%91",
        "block": "Mathematical Operators",
        "plane": "BMP",
        "age": "1.1",
        "generalCategory": "Math Symbol (Sm)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#8721;", "&#x2211;", "&sum;"],
        "utf8": "0xE2 0x88 0x91",
        "utf8HexBytes": ["E2", "88", "91"],
        "utf8DecBytes": ["226", "136", "145"],
        "utf16": "0x2211",
        "utf16HexBytes": ["2211"],
        "utf16DecBytes": ["8721"],
        "utf32": "0x00002211",
        "utf32HexBytes": ["00002211"],
        "utf32DecBytes": ["8721"],
        "bidirectionalClass": "Other Neutral (ON)",
        "bidirectionalIsMirrored": True,
        "bidirectionalMirroringGlyph": "",
        "bidirectionalControl": False,
        "pairedBracketType": "None (n)",
        "pairedBracketProperty": "∑ (U+2211)",
        "decompositionType": "None (none)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "numericType": "None (None)",
        "numericValue": "NaN",
        "numericValueParsed": None,
        "joiningType": "Non Joining (U)",
        "joiningGroup": "No_Joining_Group",
        "joiningControl": False,
        "lineBreak": "Ambiguous (Alphabetic Or Ideographic) (AI)",
        "eastAsianWidth": "East Asian Ambiguous (A)",
        "uppercase": False,
        "lowercase": False,
        "simpleUppercaseMapping": "∑ (U+2211)",
        "simpleLowercaseMapping": "∑ (U+2211)",
        "simpleTitlecaseMapping": "∑ (U+2211)",
        "simpleCaseFolding": "∑ (U+2211)",
        "script": "Common (Zyyy)",
        "scriptExtensions": ["Common (Zyyy)"],
        "hangulSyllableType": "Not Applicable (NA)",
        "indicSyllabicCategory": "Other",
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "dash": False,
        "hyphen": False,
        "quotationMark": False,
        "terminalPunctuation": False,
        "sentenceTerminal": False,
        "diacritic": False,
        "extender": False,
        "softDotted": False,
        "alphabetic": False,
        "math": True,
        "hexDigit": False,
        "asciiHexDigit": False,
        "defaultIgnorableCodePoint": False,
        "logicalOrderException": False,
        "prependedConcatenationMark": False,
        "whiteSpace": False,
        "verticalOrientation": "Rotated 90 degrees clockwise (R)",
        "regionalIndicator": False,
        "emoji": False,
        "emojiPresentation": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiComponent": False,
        "extendedPictographic": False,
    },
    "🇦": {
        "character": "🇦",
        "name": "REGIONAL INDICATOR SYMBOL LETTER A",
        "codepoint": "U+1F1E6",
        "uriEncoded": "%F0%9F%87%A6",
        "block": "Enclosed Alphanumeric Supplement",
        "plane": "SMP",
        "age": "6.0",
        "generalCategory": "Other Symbol (So)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#127462;", "&#x1F1E6;"],
        "utf8": "0xF0 0x9F 0x87 0xA6",
        "utf8HexBytes": ["F0", "9F", "87", "A6"],
        "utf8DecBytes": ["240", "159", "135", "166"],
        "utf16": "0xD83C 0xDDE6",
        "utf16HexBytes": ["D83C", "DDE6"],
        "utf16DecBytes": ["55356", "56806"],
        "utf32": "0x0001F1E6",
        "utf32HexBytes": ["0001F1E6"],
        "utf32DecBytes": ["127462"],
        "bidirectionalClass": "Left To Right (L)",
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": "",
        "bidirectionalControl": False,
        "pairedBracketType": "None (n)",
        "pairedBracketProperty": "🇦 (U+1F1E6)",
        "decompositionType": "None (none)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "numericType": "None (None)",
        "numericValue": "NaN",
        "numericValueParsed": None,
        "joiningType": "Non Joining (U)",
        "joiningGroup": "No_Joining_Group",
        "joiningControl": False,
        "lineBreak": "Unknown (XX)",
        "eastAsianWidth": "Neutral Not East Asian (N)",
        "uppercase": False,
        "lowercase": False,
        "simpleUppercaseMapping": "🇦 (U+1F1E6)",
        "simpleLowercaseMapping": "🇦 (U+1F1E6)",
        "simpleTitlecaseMapping": "🇦 (U+1F1E6)",
        "simpleCaseFolding": "🇦 (U+1F1E6)",
        "script": "Common (Zyyy)",
        "scriptExtensions": ["Common (Zyyy)"],
        "hangulSyllableType": "Not Applicable (NA)",
        "indicSyllabicCategory": "Other",
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "dash": False,
        "hyphen": False,
        "quotationMark": False,
        "terminalPunctuation": False,
        "sentenceTerminal": False,
        "diacritic": False,
        "extender": False,
        "softDotted": False,
        "alphabetic": False,
        "math": False,
        "hexDigit": False,
        "asciiHexDigit": False,
        "defaultIgnorableCodePoint": False,
        "logicalOrderException": False,
        "prependedConcatenationMark": False,
        "whiteSpace": False,
        "verticalOrientation": "Upright (U)",
        "regionalIndicator": True,
        "emoji": True,
        "emojiPresentation": True,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiComponent": True,
        "extendedPictographic": False,
    },
    "ཀྵ": {
        "character": "ཀྵ",
        "name": "TIBETAN LETTER KSSA",
        "codepoint": "U+0F69",
        "uriEncoded": "%E0%BD%A9",
        "block": "Tibetan",
        "plane": "BMP",
        "age": "2.0",
        "generalCategory": "Other Letter (Lo)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#3945;", "&#xF69;"],
        "utf8": "0xE0 0xBD 0xA9",
        "utf8HexBytes": ["E0", "BD", "A9"],
        "utf8DecBytes": ["224", "189", "169"],
        "utf16": "0x0F69",
        "utf16HexBytes": ["0F69"],
        "utf16DecBytes": ["3945"],
        "utf32": "0x00000F69",
        "utf32HexBytes": ["00000F69"],
        "utf32DecBytes": ["3945"],
        "bidirectionalClass": "Left To Right (L)",
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": "",
        "bidirectionalControl": False,
        "pairedBracketType": "None (n)",
        "pairedBracketProperty": "ཀྵ (U+0F69)",
        "decompositionType": "Canonical (can)",
        "NFC_QC": "No",
        "NFD_QC": "No",
        "NFKC_QC": "No",
        "NFKD_QC": "No",
        "numericType": "None (None)",
        "numericValue": "NaN",
        "numericValueParsed": None,
        "joiningType": "Non Joining (U)",
        "joiningGroup": "No_Joining_Group",
        "joiningControl": False,
        "lineBreak": "Ordinary Alphabetic And Symbol (AL)",
        "eastAsianWidth": "Neutral Not East Asian (N)",
        "uppercase": False,
        "lowercase": False,
        "simpleUppercaseMapping": "ཀྵ (U+0F69)",
        "simpleLowercaseMapping": "ཀྵ (U+0F69)",
        "simpleTitlecaseMapping": "ཀྵ (U+0F69)",
        "simpleCaseFolding": "ཀྵ (U+0F69)",
        "script": "Tibetan (Tibt)",
        "scriptExtensions": ["Tibetan (Tibt)"],
        "hangulSyllableType": "Not Applicable (NA)",
        "indicSyllabicCategory": "Consonant",
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "dash": False,
        "hyphen": False,
        "quotationMark": False,
        "terminalPunctuation": False,
        "sentenceTerminal": False,
        "diacritic": False,
        "extender": False,
        "softDotted": False,
        "alphabetic": True,
        "math": False,
        "hexDigit": False,
        "asciiHexDigit": False,
        "defaultIgnorableCodePoint": False,
        "logicalOrderException": False,
        "prependedConcatenationMark": False,
        "whiteSpace": False,
        "verticalOrientation": "Rotated 90 degrees clockwise (R)",
        "regionalIndicator": False,
        "emoji": False,
        "emojiPresentation": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiComponent": False,
        "extendedPictographic": False,
    },
    "🐍": {
        "character": "🐍",
        "name": "SNAKE",
        "codepoint": "U+1F40D",
        "uriEncoded": "%F0%9F%90%8D",
        "block": "Miscellaneous Symbols and Pictographs",
        "plane": "SMP",
        "age": "6.0",
        "generalCategory": "Other Symbol (So)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#128013;", "&#x1F40D;"],
        "utf8": "0xF0 0x9F 0x90 0x8D",
        "utf8HexBytes": ["F0", "9F", "90", "8D"],
        "utf8DecBytes": ["240", "159", "144", "141"],
        "utf16": "0xD83D 0xDC0D",
        "utf16HexBytes": ["D83D", "DC0D"],
        "utf16DecBytes": ["55357", "56333"],
        "utf32": "0x0001F40D",
        "utf32HexBytes": ["0001F40D"],
        "utf32DecBytes": ["128013"],
        "bidirectionalClass": "Other Neutral (ON)",
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": "",
        "bidirectionalControl": False,
        "pairedBracketType": "None (n)",
        "pairedBracketProperty": "🐍 (U+1F40D)",
        "decompositionType": "None (none)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "numericType": "None (None)",
        "numericValue": "NaN",
        "numericValueParsed": None,
        "joiningType": "Non Joining (U)",
        "joiningGroup": "No_Joining_Group",
        "joiningControl": False,
        "lineBreak": "Ideographic (ID)",
        "eastAsianWidth": "East Asian Wide (W)",
        "uppercase": False,
        "lowercase": False,
        "simpleUppercaseMapping": "🐍 (U+1F40D)",
        "simpleLowercaseMapping": "🐍 (U+1F40D)",
        "simpleTitlecaseMapping": "🐍 (U+1F40D)",
        "simpleCaseFolding": "🐍 (U+1F40D)",
        "script": "Common (Zyyy)",
        "scriptExtensions": ["Common (Zyyy)"],
        "hangulSyllableType": "Not Applicable (NA)",
        "indicSyllabicCategory": "Other",
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "dash": False,
        "hyphen": False,
        "quotationMark": False,
        "terminalPunctuation": False,
        "sentenceTerminal": False,
        "diacritic": False,
        "extender": False,
        "softDotted": False,
        "alphabetic": False,
        "math": False,
        "hexDigit": False,
        "asciiHexDigit": False,
        "defaultIgnorableCodePoint": False,
        "logicalOrderException": False,
        "prependedConcatenationMark": False,
        "whiteSpace": False,
        "verticalOrientation": "Upright (U)",
        "regionalIndicator": False,
        "emoji": True,
        "emojiPresentation": True,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiComponent": False,
        "extendedPictographic": True,
    },
    "櫓": {
        "character": "櫓",
        "name": "CJK COMPATIBILITY IDEOGRAPH-F931",
        "codepoint": "U+F931",
        "uriEncoded": "%EF%A4%B1",
        "block": "CJK Compatibility Ideographs",
        "plane": "BMP",
        "age": "1.1",
        "generalCategory": "Other Letter (Lo)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#63793;", "&#xF931;"],
        "utf8": "0xEF 0xA4 0xB1",
        "utf8HexBytes": ["EF", "A4", "B1"],
        "utf8DecBytes": ["239", "164", "177"],
        "utf16": "0xF931",
        "utf16HexBytes": ["F931"],
        "utf16DecBytes": ["63793"],
        "utf32": "0x0000F931",
        "utf32HexBytes": ["0000F931"],
        "utf32DecBytes": ["63793"],
        "bidirectionalClass": "Left To Right (L)",
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": "",
        "bidirectionalControl": False,
        "pairedBracketType": "None (n)",
        "pairedBracketProperty": "櫓 (U+F931)",
        "decompositionType": "Canonical (can)",
        "NFC_QC": "No",
        "NFD_QC": "No",
        "NFKC_QC": "No",
        "NFKD_QC": "No",
        "numericType": "None (None)",
        "numericValue": "NaN",
        "numericValueParsed": None,
        "joiningType": "Non Joining (U)",
        "joiningGroup": "No_Joining_Group",
        "joiningControl": False,
        "lineBreak": "Ideographic (ID)",
        "eastAsianWidth": "East Asian Wide (W)",
        "uppercase": False,
        "lowercase": False,
        "simpleUppercaseMapping": "櫓 (U+F931)",
        "simpleLowercaseMapping": "櫓 (U+F931)",
        "simpleTitlecaseMapping": "櫓 (U+F931)",
        "simpleCaseFolding": "櫓 (U+F931)",
        "script": "Han (Hani)",
        "scriptExtensions": ["Han (Hani)"],
        "hangulSyllableType": "Not Applicable (NA)",
        "indicSyllabicCategory": "Other",
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "dash": False,
        "hyphen": False,
        "quotationMark": False,
        "terminalPunctuation": False,
        "sentenceTerminal": False,
        "diacritic": False,
        "extender": False,
        "softDotted": False,
        "alphabetic": True,
        "math": False,
        "hexDigit": False,
        "asciiHexDigit": False,
        "defaultIgnorableCodePoint": False,
        "logicalOrderException": False,
        "prependedConcatenationMark": False,
        "whiteSpace": False,
        "verticalOrientation": "Upright (U)",
        "regionalIndicator": False,
        "emoji": False,
        "emojiPresentation": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiComponent": False,
        "extendedPictographic": False,
    },
    "(": {
        "character": "(",
        "name": "LEFT PARENTHESIS",
        "codepoint": "U+0028",
        "uriEncoded": "%28",
        "block": "Basic Latin",
        "plane": "BMP",
        "age": "1.1",
        "generalCategory": "Open Punctuation (Ps)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#40;", "&#x28;", "&lpar;"],
        "utf8": "0x28",
        "utf8HexBytes": ["28"],
        "utf8DecBytes": ["40"],
        "utf16": "0x0028",
        "utf16HexBytes": ["0028"],
        "utf16DecBytes": ["40"],
        "utf32": "0x00000028",
        "utf32HexBytes": ["00000028"],
        "utf32DecBytes": ["40"],
        "bidirectionalClass": "Other Neutral (ON)",
        "bidirectionalIsMirrored": True,
        "bidirectionalMirroringGlyph": ") (U+0029)",
        "bidirectionalControl": False,
        "pairedBracketType": "Open (o)",
        "pairedBracketProperty": ") (U+0029)",
        "decompositionType": "None (none)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "numericType": "None (None)",
        "numericValue": "NaN",
        "numericValueParsed": None,
        "joiningType": "Non Joining (U)",
        "joiningGroup": "No_Joining_Group",
        "joiningControl": False,
        "lineBreak": "Opening Punctuation (OP)",
        "eastAsianWidth": "East Asian Narrow (Na)",
        "uppercase": False,
        "lowercase": False,
        "simpleUppercaseMapping": "( (U+0028)",
        "simpleLowercaseMapping": "( (U+0028)",
        "simpleTitlecaseMapping": "( (U+0028)",
        "simpleCaseFolding": "( (U+0028)",
        "script": "Common (Zyyy)",
        "scriptExtensions": ["Common (Zyyy)"],
        "hangulSyllableType": "Not Applicable (NA)",
        "indicSyllabicCategory": "Other",
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "dash": False,
        "hyphen": False,
        "quotationMark": False,
        "terminalPunctuation": False,
        "sentenceTerminal": False,
        "diacritic": False,
        "extender": False,
        "softDotted": False,
        "alphabetic": False,
        "math": False,
        "hexDigit": False,
        "asciiHexDigit": False,
        "defaultIgnorableCodePoint": False,
        "logicalOrderException": False,
        "prependedConcatenationMark": False,
        "whiteSpace": False,
        "verticalOrientation": "Rotated 90 degrees clockwise (R)",
        "regionalIndicator": False,
        "emoji": False,
        "emojiPresentation": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiComponent": False,
        "extendedPictographic": False,
    },
    "￾": {
        "character": "￾",
        "name": "<noncharacter-FFFE>",
        "codepoint": "U+FFFE",
        "uriEncoded": "%EF%BF%BE",
        "block": "Specials",
        "plane": "BMP",
        "age": "1.1",
        "generalCategory": "Private Use (Co)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#65534;", "&#xFFFE;"],
        "utf8": "0xEF 0xBF 0xBE",
        "utf8HexBytes": ["EF", "BF", "BE"],
        "utf8DecBytes": ["239", "191", "190"],
        "utf16": "0xFFFE",
        "utf16HexBytes": ["FFFE"],
        "utf16DecBytes": ["65534"],
        "utf32": "0x0000FFFE",
        "utf32HexBytes": ["0000FFFE"],
        "utf32DecBytes": ["65534"],
        "bidirectionalClass": "Left To Right (L)",
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": "￾ (U+FFFE)",
        "bidirectionalControl": False,
        "pairedBracketType": "None (n)",
        "pairedBracketProperty": "",
        "decompositionType": "None (none)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "numericType": "None (None)",
        "numericValue": "",
        "numericValueParsed": 0.0,
        "joiningType": "Non Joining (U)",
        "joiningGroup": "",
        "joiningControl": False,
        "lineBreak": "Unknown (XX)",
        "eastAsianWidth": "East Asian Ambiguous (A)",
        "uppercase": False,
        "lowercase": False,
        "simpleUppercaseMapping": "",
        "simpleLowercaseMapping": "",
        "simpleTitlecaseMapping": "",
        "simpleCaseFolding": "",
        "script": "Unknown (Zzzz)",
        "scriptExtensions": ["Unknown (Zzzz)"],
        "hangulSyllableType": "Not Applicable (NA)",
        "indicSyllabicCategory": "",
        "indicMatraCategory": "",
        "indicPositionalCategory": "",
        "dash": False,
        "hyphen": False,
        "quotationMark": False,
        "terminalPunctuation": False,
        "sentenceTerminal": False,
        "diacritic": False,
        "extender": False,
        "softDotted": False,
        "alphabetic": False,
        "math": False,
        "hexDigit": False,
        "asciiHexDigit": False,
        "defaultIgnorableCodePoint": False,
        "logicalOrderException": False,
        "prependedConcatenationMark": False,
        "whiteSpace": False,
        "verticalOrientation": "Upright (U)",
        "regionalIndicator": False,
        "emoji": False,
        "emojiPresentation": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiComponent": False,
        "extendedPictographic": False,
    },
    "": {
        "character": "",
        "name": "<private-use-F800>",
        "codepoint": "U+F800",
        "uriEncoded": "%EF%A0%80",
        "block": "Private Use Area",
        "plane": "BMP",
        "age": "1.1",
        "generalCategory": "Private Use (Co)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#63488;", "&#xF800;"],
        "utf8": "0xEF 0xA0 0x80",
        "utf8HexBytes": ["EF", "A0", "80"],
        "utf8DecBytes": ["239", "160", "128"],
        "utf16": "0xF800",
        "utf16HexBytes": ["F800"],
        "utf16DecBytes": ["63488"],
        "utf32": "0x0000F800",
        "utf32HexBytes": ["0000F800"],
        "utf32DecBytes": ["63488"],
        "bidirectionalClass": "Left To Right (L)",
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": " (U+F800)",
        "bidirectionalControl": False,
        "pairedBracketType": "None (n)",
        "pairedBracketProperty": "",
        "decompositionType": "None (none)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "numericType": "None (None)",
        "numericValue": "",
        "numericValueParsed": 0,
        "joiningType": "Non Joining (U)",
        "joiningGroup": "",
        "joiningControl": False,
        "lineBreak": "Unknown (XX)",
        "eastAsianWidth": "East Asian Ambiguous (A)",
        "uppercase": False,
        "lowercase": False,
        "simpleUppercaseMapping": "",
        "simpleLowercaseMapping": "",
        "simpleTitlecaseMapping": "",
        "simpleCaseFolding": "",
        "script": "Unknown (Zzzz)",
        "scriptExtensions": ["Unknown (Zzzz)"],
        "hangulSyllableType": "Not Applicable (NA)",
        "indicSyllabicCategory": "",
        "indicMatraCategory": "",
        "indicPositionalCategory": "",
        "dash": False,
        "hyphen": False,
        "quotationMark": False,
        "terminalPunctuation": False,
        "sentenceTerminal": False,
        "diacritic": False,
        "extender": False,
        "softDotted": False,
        "alphabetic": False,
        "math": False,
        "hexDigit": False,
        "asciiHexDigit": False,
        "defaultIgnorableCodePoint": False,
        "logicalOrderException": False,
        "prependedConcatenationMark": False,
        "whiteSpace": False,
        "verticalOrientation": "Upright (U)",
        "regionalIndicator": False,
        "emoji": False,
        "emojiPresentation": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiComponent": False,
        "extendedPictographic": False,
    },
    "\u0017": {
        "character": "␗",
        "name": "<control-0017> END OF TRANSMISSION BLOCK (ETB)",
        "codepoint": "U+0017",
        "uriEncoded": "%17",
        "block": "Basic Latin",
        "plane": "BMP",
        "age": "1.1",
        "generalCategory": "Control (Cc)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#23;", "&#x17;"],
        "utf8": "0x17",
        "utf8HexBytes": ["17"],
        "utf8DecBytes": ["23"],
        "utf16": "0x0017",
        "utf16HexBytes": ["0017"],
        "utf16DecBytes": ["23"],
        "utf32": "0x00000017",
        "utf32HexBytes": ["00000017"],
        "utf32DecBytes": ["23"],
        "bidirectionalClass": "Boundary Neutral (BN)",
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": "",
        "bidirectionalControl": False,
        "pairedBracketType": "None (n)",
        "pairedBracketProperty": "\u0017 (U+0017)",
        "decompositionType": "None (none)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "numericType": "None (None)",
        "numericValue": "NaN",
        "numericValueParsed": None,
        "joiningType": "Non Joining (U)",
        "joiningGroup": "No_Joining_Group",
        "joiningControl": False,
        "lineBreak": "Attached Characters And Combining Marks (CM)",
        "eastAsianWidth": "Neutral Not East Asian (N)",
        "uppercase": False,
        "lowercase": False,
        "simpleUppercaseMapping": "\u0017 (U+0017)",
        "simpleLowercaseMapping": "\u0017 (U+0017)",
        "simpleTitlecaseMapping": "\u0017 (U+0017)",
        "simpleCaseFolding": "\u0017 (U+0017)",
        "script": "Common (Zyyy)",
        "scriptExtensions": ["Common (Zyyy)"],
        "hangulSyllableType": "Not Applicable (NA)",
        "indicSyllabicCategory": "Other",
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "dash": False,
        "hyphen": False,
        "quotationMark": False,
        "terminalPunctuation": False,
        "sentenceTerminal": False,
        "diacritic": False,
        "extender": False,
        "softDotted": False,
        "alphabetic": False,
        "math": False,
        "hexDigit": False,
        "asciiHexDigit": False,
        "defaultIgnorableCodePoint": False,
        "logicalOrderException": False,
        "prependedConcatenationMark": False,
        "whiteSpace": False,
        "verticalOrientation": "Rotated 90 degrees clockwise (R)",
        "regionalIndicator": False,
        "emoji": False,
        "emojiPresentation": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiComponent": False,
        "extendedPictographic": False,
    },
}


def get_all_prop_names():
    prop_names = {cls.normalized for cls in CharPropertyGroup}
    prop_aliases = {cls.short_alias for cls in CharPropertyGroup}
    prop_names.update(prop_aliases)
    return list(prop_names)


ALL_PROP_GROUP_NAMES = get_all_prop_names()

INVALID_PROP_GROUP_NAMES = {
    "detail": "3 values provided for the 'show_props' parameter are invalid: ['foo', 'bar', 'baz']"
}
