from app.schemas.enums import CharPropertyGroup

CHARACTER_PROPERTIES = {
    "\u0017": {
        "character": "␗",
        "name": "<control-0017> END OF TRANSMISSION BLOCK (ETB)",
        "codepoint": "U+0017",
        "uriEncoded": "%17",
        "block": "Basic Latin",
        "plane": "BMP",
        "age": "1.1",
        "generalCategory": "Control (Cc)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#23;", "&#x17;"],
        "utf8": "0x17",
        "utf8HexBytes": ["17"],
        "utf8DecBytes": ["23"],
        "utf16": "0x0017",
        "utf16HexBytes": ["0017"],
        "utf16DecBytes": ["23"],
        "utf32": "0x00000017",
        "utf32HexBytes": ["00000017"],
        "utf32DecBytes": ["23"],
        "bidirectionalClass": "Boundary Neutral (BN)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "lineBreak": "Attached Characters And Combining Marks (CM)",
        "eastAsianWidth": "Neutral Not East Asian (N)",
        "script": "Common (Zyyy)",
        "scriptExtensions": ["Common (Zyyy)"],
        "verticalOrientation": "Rotated 90 degrees clockwise (R)",
    },
    "(": {
        "character": "(",
        "name": "LEFT PARENTHESIS",
        "codepoint": "U+0028",
        "uriEncoded": "%28",
        "block": "Basic Latin",
        "plane": "BMP",
        "age": "1.1",
        "generalCategory": "Open Punctuation (Ps)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#40;", "&#x28;", "&lpar;"],
        "utf8": "0x28",
        "utf8HexBytes": ["28"],
        "utf8DecBytes": ["40"],
        "utf16": "0x0028",
        "utf16HexBytes": ["0028"],
        "utf16DecBytes": ["40"],
        "utf32": "0x00000028",
        "utf32HexBytes": ["00000028"],
        "utf32DecBytes": ["40"],
        "bidirectionalClass": "Other Neutral (ON)",
        "bidirectionalIsMirrored": True,
        "bidirectionalMirroringGlyph": ") (U+0029 RIGHT PARENTHESIS)",
        "pairedBracketType": "Open (o)",
        "pairedBracketProperty": ") (U+0029 RIGHT PARENTHESIS)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "lineBreak": "Opening Punctuation (OP)",
        "eastAsianWidth": "East Asian Narrow (Na)",
        "script": "Common (Zyyy)",
        "scriptExtensions": ["Common (Zyyy)"],
        "verticalOrientation": "Rotated 90 degrees clockwise (R)",
    },
    "∑": {
        "character": "∑",
        "name": "N-ARY SUMMATION",
        "codepoint": "U+2211",
        "uriEncoded": "%E2%88%91",
        "block": "Mathematical Operators",
        "plane": "BMP",
        "age": "1.1",
        "generalCategory": "Math Symbol (Sm)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#8721;", "&#x2211;", "&sum;"],
        "utf8": "0xE2 0x88 0x91",
        "utf8HexBytes": ["E2", "88", "91"],
        "utf8DecBytes": ["226", "136", "145"],
        "utf16": "0x2211",
        "utf16HexBytes": ["2211"],
        "utf16DecBytes": ["8721"],
        "utf32": "0x00002211",
        "utf32HexBytes": ["00002211"],
        "utf32DecBytes": ["8721"],
        "bidirectionalClass": "Other Neutral (ON)",
        "bidirectionalIsMirrored": True,
        "bidirectionalMirroringGlyph": "∑ (U+2211 N-ARY SUMMATION)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "lineBreak": "Ambiguous (Alphabetic Or Ideographic) (AI)",
        "eastAsianWidth": "East Asian Ambiguous (A)",
        "script": "Common (Zyyy)",
        "scriptExtensions": ["Common (Zyyy)"],
        "math": True,
        "verticalOrientation": "Rotated 90 degrees clockwise (R)",
    },
    "㑢": {
        "utf8": "0xE3 0x91 0xA2",
        "utf8HexBytes": ["E3", "91", "A2"],
        "utf8DecBytes": ["227", "145", "162"],
        "utf16": "0x3462",
        "utf16HexBytes": ["3462"],
        "utf16DecBytes": ["13410"],
        "utf32": "0x00003462",
        "utf32HexBytes": ["00003462"],
        "utf32DecBytes": ["13410"],
        "bidirectionalClass": "Left To Right (L)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "lineBreak": "Ideographic (ID)",
        "eastAsianWidth": "East Asian Wide (W)",
        "script": "Han (Hani)",
        "scriptExtensions": ["Han (Hani)"],
        "character": "㑢",
        "name": "CJK UNIFIED IDEOGRAPH-3462",
        "codepoint": "U+3462",
        "uriEncoded": "%E3%91%A2",
        "block": "CJK Unified Ideographs Extension A",
        "plane": "BMP",
        "age": "3.0",
        "generalCategory": "Other Letter (Lo)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#13410;", "&#x3462;"],
        "rsCountUnicode": "9.7",
        "totalStrokes": [9],
        "cantonese": "koek3",
        "ideographic": True,
        "unifiedIdeograph": True,
        "alphabetic": True,
        "verticalOrientation": "Upright (U)",
    },
    "穩": {
        "utf8": "0xE7 0xA9 0xA9",
        "utf8HexBytes": ["E7", "A9", "A9"],
        "utf8DecBytes": ["231", "169", "169"],
        "utf16": "0x7A69",
        "utf16HexBytes": ["7A69"],
        "utf16DecBytes": ["31337"],
        "utf32": "0x00007A69",
        "utf32HexBytes": ["00007A69"],
        "utf32DecBytes": ["31337"],
        "bidirectionalClass": "Left To Right (L)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "lineBreak": "Ideographic (ID)",
        "eastAsianWidth": "East Asian Wide (W)",
        "script": "Han (Hani)",
        "scriptExtensions": ["Han (Hani)"],
        "character": "穩",
        "name": "CJK UNIFIED IDEOGRAPH-7A69",
        "description": "stable, firm, solid, steady",
        "codepoint": "U+7A69",
        "uriEncoded": "%E7%A9%A9",
        "block": "CJK Unified Ideographs",
        "plane": "BMP",
        "age": "1.1",
        "generalCategory": "Other Letter (Lo)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#31337;", "&#x7A69;"],
        "ideoFrequency": 4,
        "ideoGradeLevel": 5,
        "rsCountUnicode": "115.14",
        "rsCountKangxi": "115.14",
        "totalStrokes": [19],
        "simplifiedVariant": ["稳 (U+7A33 CJK UNIFIED IDEOGRAPH-7A33)"],
        "semanticVariant": ["㒚 (U+349A CJK UNIFIED IDEOGRAPH-349A)"],
        "specializedSemanticVariant": ["文 (U+6587 CJK UNIFIED IDEOGRAPH-6587)"],
        "hangul": "온:0N",
        "cantonese": "wan2",
        "mandarin": "wěn",
        "japaneseKun": "ODAYAKA",
        "japaneseOn": "ON",
        "vietnamese": "ủn",
        "ideographic": True,
        "unifiedIdeograph": True,
        "alphabetic": True,
        "verticalOrientation": "Upright (U)",
    },
    "范": {
        "utf8": "0xE8 0x8C 0x83",
        "utf8HexBytes": ["E8", "8C", "83"],
        "utf8DecBytes": ["232", "140", "131"],
        "utf16": "0x8303",
        "utf16HexBytes": ["8303"],
        "utf16DecBytes": ["33539"],
        "utf32": "0x00008303",
        "utf32HexBytes": ["00008303"],
        "utf32DecBytes": ["33539"],
        "bidirectionalClass": "Left To Right (L)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "lineBreak": "Ideographic (ID)",
        "eastAsianWidth": "East Asian Wide (W)",
        "script": "Han (Hani)",
        "scriptExtensions": ["Han (Hani)"],
        "character": "范",
        "name": "CJK UNIFIED IDEOGRAPH-8303",
        "description": "surname, bee-like insect",
        "codepoint": "U+8303",
        "uriEncoded": "%E8%8C%83",
        "block": "CJK Unified Ideographs",
        "plane": "BMP",
        "age": "1.1",
        "generalCategory": "Other Letter (Lo)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#33539;", "&#x8303;"],
        "ideoFrequency": 5,
        "rsCountUnicode": "140.5",
        "rsCountKangxi": "140.5",
        "totalStrokes": [8, 9],
        "traditionalVariant": ["範 (U+7BC4 CJK UNIFIED IDEOGRAPH-7BC4)", "范 (U+8303 CJK UNIFIED IDEOGRAPH-8303)"],
        "simplifiedVariant": ["范 (U+8303 CJK UNIFIED IDEOGRAPH-8303)"],
        "hangul": "범:0N",
        "cantonese": "faan6",
        "mandarin": "fàn",
        "japaneseKun": "HACHI IGATA NORI",
        "japaneseOn": "HAN HON",
        "ideographic": True,
        "unifiedIdeograph": True,
        "alphabetic": True,
        "verticalOrientation": "Upright (U)",
    },
    "𑿀": {
        "character": "𑿀",
        "name": "TAMIL FRACTION ONE THREE-HUNDRED-AND-TWENTIETH",
        "codepoint": "U+11FC0",
        "uriEncoded": "%F0%91%BF%80",
        "block": "Tamil Supplement",
        "plane": "SMP",
        "age": "12.0",
        "generalCategory": "Other Number (No)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#73664;", "&#x11FC0;"],
        "utf8": "0xF0 0x91 0xBF 0x80",
        "utf8HexBytes": ["F0", "91", "BF", "80"],
        "utf8DecBytes": ["240", "145", "191", "128"],
        "utf16": "0xD807 0xDFC0",
        "utf16HexBytes": ["D807", "DFC0"],
        "utf16DecBytes": ["55303", "57280"],
        "utf32": "0x00011FC0",
        "utf32HexBytes": ["00011FC0"],
        "utf32DecBytes": ["73664"],
        "bidirectionalClass": "Left To Right (L)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "numericType": "Numeric (Nu)",
        "numericValue": ["1/320"],
        "numericValueParsed": [0.003125],
        "lineBreak": "Ordinary Alphabetic And Symbol (AL)",
        "eastAsianWidth": "Neutral Not East Asian (N)",
        "script": "Tamil (Taml)",
        "scriptExtensions": ["Tamil (Taml)"],
        "verticalOrientation": "Rotated 90 degrees clockwise (R)",
    },
    "": {
        "character": "",
        "name": "<private-use-F800>",
        "codepoint": "U+F800",
        "uriEncoded": "%EF%A0%80",
        "block": "Private Use Area",
        "plane": "BMP",
        "age": "1.1",
        "generalCategory": "Private Use (Co)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#63488;", "&#xF800;"],
        "utf8": "0xEF 0xA0 0x80",
        "utf8HexBytes": ["EF", "A0", "80"],
        "utf8DecBytes": ["239", "160", "128"],
        "utf16": "0xF800",
        "utf16HexBytes": ["F800"],
        "utf16DecBytes": ["63488"],
        "utf32": "0x0000F800",
        "utf32HexBytes": ["0000F800"],
        "utf32DecBytes": ["63488"],
        "bidirectionalClass": "Left To Right (L)",
        "pairedBracketType": "None (n)",
        "pairedBracketProperty": "",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "lineBreak": "Unknown (XX)",
        "eastAsianWidth": "East Asian Ambiguous (A)",
        "script": "Unknown (Zzzz)",
        "scriptExtensions": ["Unknown (Zzzz)"],
        "indicSyllabicCategory": "",
        "indicMatraCategory": "",
        "indicPositionalCategory": "",
        "verticalOrientation": "Upright (U)",
    },
    "￾": {
        "character": "￾",
        "name": "<noncharacter-FFFE>",
        "codepoint": "U+FFFE",
        "uriEncoded": "%EF%BF%BE",
        "block": "Specials",
        "plane": "BMP",
        "age": "1.1",
        "generalCategory": "Unassigned (Cn)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#65534;", "&#xFFFE;"],
        "utf8": "0xEF 0xBF 0xBE",
        "utf8HexBytes": ["EF", "BF", "BE"],
        "utf8DecBytes": ["239", "191", "190"],
        "utf16": "0xFFFE",
        "utf16HexBytes": ["FFFE"],
        "utf16DecBytes": ["65534"],
        "utf32": "0x0000FFFE",
        "utf32HexBytes": ["0000FFFE"],
        "utf32DecBytes": ["65534"],
        "bidirectionalClass": "Left To Right (L)",
        "pairedBracketType": "None (n)",
        "pairedBracketProperty": "",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "lineBreak": "Unknown (XX)",
        "eastAsianWidth": "East Asian Ambiguous (A)",
        "script": "Unknown (Zzzz)",
        "scriptExtensions": ["Unknown (Zzzz)"],
        "indicSyllabicCategory": "",
        "indicMatraCategory": "",
        "indicPositionalCategory": "",
        "verticalOrientation": "Upright (U)",
    },
    "🇦": {
        "character": "🇦",
        "name": "REGIONAL INDICATOR SYMBOL LETTER A",
        "codepoint": "U+1F1E6",
        "uriEncoded": "%F0%9F%87%A6",
        "block": "Enclosed Alphanumeric Supplement",
        "plane": "SMP",
        "age": "6.0",
        "generalCategory": "Other Symbol (So)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#127462;", "&#x1F1E6;"],
        "utf8": "0xF0 0x9F 0x87 0xA6",
        "utf8HexBytes": ["F0", "9F", "87", "A6"],
        "utf8DecBytes": ["240", "159", "135", "166"],
        "utf16": "0xD83C 0xDDE6",
        "utf16HexBytes": ["D83C", "DDE6"],
        "utf16DecBytes": ["55356", "56806"],
        "utf32": "0x0001F1E6",
        "utf32HexBytes": ["0001F1E6"],
        "utf32DecBytes": ["127462"],
        "bidirectionalClass": "Left To Right (L)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "lineBreak": "Unknown (XX)",
        "eastAsianWidth": "Neutral Not East Asian (N)",
        "script": "Common (Zyyy)",
        "scriptExtensions": ["Common (Zyyy)"],
        "verticalOrientation": "Upright (U)",
        "regionalIndicator": True,
        "emoji": True,
        "emojiPresentation": True,
        "emojiComponent": True,
    },
    "🐍": {
        "character": "🐍",
        "name": "SNAKE",
        "codepoint": "U+1F40D",
        "uriEncoded": "%F0%9F%90%8D",
        "block": "Miscellaneous Symbols and Pictographs",
        "plane": "SMP",
        "age": "6.0",
        "generalCategory": "Other Symbol (So)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#128013;", "&#x1F40D;"],
        "utf8": "0xF0 0x9F 0x90 0x8D",
        "utf8HexBytes": ["F0", "9F", "90", "8D"],
        "utf8DecBytes": ["240", "159", "144", "141"],
        "utf16": "0xD83D 0xDC0D",
        "utf16HexBytes": ["D83D", "DC0D"],
        "utf16DecBytes": ["55357", "56333"],
        "utf32": "0x0001F40D",
        "utf32HexBytes": ["0001F40D"],
        "utf32DecBytes": ["128013"],
        "bidirectionalClass": "Other Neutral (ON)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "lineBreak": "Ideographic (ID)",
        "eastAsianWidth": "East Asian Wide (W)",
        "script": "Common (Zyyy)",
        "scriptExtensions": ["Common (Zyyy)"],
        "verticalOrientation": "Upright (U)",
        "emoji": True,
        "emojiPresentation": True,
        "extendedPictographic": True,
    },
}

VERBOSE_CHARACTER_PROPERTIES = {
    "\u0017": {
        "character": "␗",
        "name": "<control-0017> END OF TRANSMISSION BLOCK (ETB)",
        "codepoint": "U+0017",
        "uriEncoded": "%17",
        "block": "Basic Latin",
        "plane": "BMP",
        "age": "1.1",
        "generalCategory": "Control (Cc)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#23;", "&#x17;"],
        "utf8": "0x17",
        "utf8HexBytes": ["17"],
        "utf8DecBytes": ["23"],
        "utf16": "0x0017",
        "utf16HexBytes": ["0017"],
        "utf16DecBytes": ["23"],
        "utf32": "0x00000017",
        "utf32HexBytes": ["00000017"],
        "utf32DecBytes": ["23"],
        "bidirectionalClass": "Boundary Neutral (BN)",
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": "\u0017 (U+0017 <control-0017> END OF TRANSMISSION BLOCK (ETB))",
        "bidirectionalControl": False,
        "pairedBracketType": "None (n)",
        "pairedBracketProperty": "\u0017 (U+0017 <control-0017> END OF TRANSMISSION BLOCK (ETB))",
        "decompositionType": "None (none)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "numericType": "None (None)",
        "numericValue": ["NaN"],
        "numericValueParsed": [],
        "joiningType": "Non Joining (U)",
        "joiningGroup": "No_Joining_Group",
        "joiningControl": False,
        "lineBreak": "Attached Characters And Combining Marks (CM)",
        "eastAsianWidth": "Neutral Not East Asian (N)",
        "uppercase": False,
        "lowercase": False,
        "simpleUppercaseMapping": "\u0017 (U+0017 <control-0017> END OF TRANSMISSION BLOCK (ETB))",
        "simpleLowercaseMapping": "\u0017 (U+0017 <control-0017> END OF TRANSMISSION BLOCK (ETB))",
        "simpleTitlecaseMapping": "\u0017 (U+0017 <control-0017> END OF TRANSMISSION BLOCK (ETB))",
        "simpleCaseFolding": "\u0017 (U+0017 <control-0017> END OF TRANSMISSION BLOCK (ETB))",
        "script": "Common (Zyyy)",
        "scriptExtensions": ["Common (Zyyy)"],
        "hangulSyllableType": "Not Applicable (NA)",
        "indicSyllabicCategory": "Other",
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "ideographic": False,
        "unifiedIdeograph": False,
        "equivalentUnifiedIdeograph": "",
        "radical": False,
        "dash": False,
        "hyphen": False,
        "quotationMark": False,
        "terminalPunctuation": False,
        "sentenceTerminal": False,
        "diacritic": False,
        "extender": False,
        "softDotted": False,
        "alphabetic": False,
        "math": False,
        "hexDigit": False,
        "asciiHexDigit": False,
        "defaultIgnorableCodePoint": False,
        "logicalOrderException": False,
        "prependedConcatenationMark": False,
        "whiteSpace": False,
        "verticalOrientation": "Rotated 90 degrees clockwise (R)",
        "regionalIndicator": False,
        "emoji": False,
        "emojiPresentation": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiComponent": False,
        "extendedPictographic": False,
    },
    "(": {
        "character": "(",
        "name": "LEFT PARENTHESIS",
        "codepoint": "U+0028",
        "uriEncoded": "%28",
        "block": "Basic Latin",
        "plane": "BMP",
        "age": "1.1",
        "generalCategory": "Open Punctuation (Ps)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#40;", "&#x28;", "&lpar;"],
        "utf8": "0x28",
        "utf8HexBytes": ["28"],
        "utf8DecBytes": ["40"],
        "utf16": "0x0028",
        "utf16HexBytes": ["0028"],
        "utf16DecBytes": ["40"],
        "utf32": "0x00000028",
        "utf32HexBytes": ["00000028"],
        "utf32DecBytes": ["40"],
        "bidirectionalClass": "Other Neutral (ON)",
        "bidirectionalIsMirrored": True,
        "bidirectionalMirroringGlyph": ") (U+0029 RIGHT PARENTHESIS)",
        "bidirectionalControl": False,
        "pairedBracketType": "Open (o)",
        "pairedBracketProperty": ") (U+0029 RIGHT PARENTHESIS)",
        "decompositionType": "None (none)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "numericType": "None (None)",
        "numericValue": ["NaN"],
        "numericValueParsed": [],
        "joiningType": "Non Joining (U)",
        "joiningGroup": "No_Joining_Group",
        "joiningControl": False,
        "lineBreak": "Opening Punctuation (OP)",
        "eastAsianWidth": "East Asian Narrow (Na)",
        "uppercase": False,
        "lowercase": False,
        "simpleUppercaseMapping": "( (U+0028 LEFT PARENTHESIS)",
        "simpleLowercaseMapping": "( (U+0028 LEFT PARENTHESIS)",
        "simpleTitlecaseMapping": "( (U+0028 LEFT PARENTHESIS)",
        "simpleCaseFolding": "( (U+0028 LEFT PARENTHESIS)",
        "script": "Common (Zyyy)",
        "scriptExtensions": ["Common (Zyyy)"],
        "hangulSyllableType": "Not Applicable (NA)",
        "indicSyllabicCategory": "Other",
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "ideographic": False,
        "unifiedIdeograph": False,
        "equivalentUnifiedIdeograph": "",
        "radical": False,
        "dash": False,
        "hyphen": False,
        "quotationMark": False,
        "terminalPunctuation": False,
        "sentenceTerminal": False,
        "diacritic": False,
        "extender": False,
        "softDotted": False,
        "alphabetic": False,
        "math": False,
        "hexDigit": False,
        "asciiHexDigit": False,
        "defaultIgnorableCodePoint": False,
        "logicalOrderException": False,
        "prependedConcatenationMark": False,
        "whiteSpace": False,
        "verticalOrientation": "Rotated 90 degrees clockwise (R)",
        "regionalIndicator": False,
        "emoji": False,
        "emojiPresentation": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiComponent": False,
        "extendedPictographic": False,
    },
    "∑": {
        "character": "∑",
        "name": "N-ARY SUMMATION",
        "codepoint": "U+2211",
        "uriEncoded": "%E2%88%91",
        "block": "Mathematical Operators",
        "plane": "BMP",
        "age": "1.1",
        "generalCategory": "Math Symbol (Sm)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#8721;", "&#x2211;", "&sum;"],
        "utf8": "0xE2 0x88 0x91",
        "utf8HexBytes": ["E2", "88", "91"],
        "utf8DecBytes": ["226", "136", "145"],
        "utf16": "0x2211",
        "utf16HexBytes": ["2211"],
        "utf16DecBytes": ["8721"],
        "utf32": "0x00002211",
        "utf32HexBytes": ["00002211"],
        "utf32DecBytes": ["8721"],
        "bidirectionalClass": "Other Neutral (ON)",
        "bidirectionalIsMirrored": True,
        "bidirectionalMirroringGlyph": "∑ (U+2211 N-ARY SUMMATION)",
        "bidirectionalControl": False,
        "pairedBracketType": "None (n)",
        "pairedBracketProperty": "∑ (U+2211 N-ARY SUMMATION)",
        "decompositionType": "None (none)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "numericType": "None (None)",
        "numericValue": ["NaN"],
        "numericValueParsed": [],
        "joiningType": "Non Joining (U)",
        "joiningGroup": "No_Joining_Group",
        "joiningControl": False,
        "lineBreak": "Ambiguous (Alphabetic Or Ideographic) (AI)",
        "eastAsianWidth": "East Asian Ambiguous (A)",
        "uppercase": False,
        "lowercase": False,
        "simpleUppercaseMapping": "∑ (U+2211 N-ARY SUMMATION)",
        "simpleLowercaseMapping": "∑ (U+2211 N-ARY SUMMATION)",
        "simpleTitlecaseMapping": "∑ (U+2211 N-ARY SUMMATION)",
        "simpleCaseFolding": "∑ (U+2211 N-ARY SUMMATION)",
        "script": "Common (Zyyy)",
        "scriptExtensions": ["Common (Zyyy)"],
        "hangulSyllableType": "Not Applicable (NA)",
        "indicSyllabicCategory": "Other",
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "ideographic": False,
        "unifiedIdeograph": False,
        "equivalentUnifiedIdeograph": "",
        "radical": False,
        "dash": False,
        "hyphen": False,
        "quotationMark": False,
        "terminalPunctuation": False,
        "sentenceTerminal": False,
        "diacritic": False,
        "extender": False,
        "softDotted": False,
        "alphabetic": False,
        "math": True,
        "hexDigit": False,
        "asciiHexDigit": False,
        "defaultIgnorableCodePoint": False,
        "logicalOrderException": False,
        "prependedConcatenationMark": False,
        "whiteSpace": False,
        "verticalOrientation": "Rotated 90 degrees clockwise (R)",
        "regionalIndicator": False,
        "emoji": False,
        "emojiPresentation": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiComponent": False,
        "extendedPictographic": False,
    },
    "㑢": {
        "utf8": "0xE3 0x91 0xA2",
        "utf8HexBytes": ["E3", "91", "A2"],
        "utf8DecBytes": ["227", "145", "162"],
        "utf16": "0x3462",
        "utf16HexBytes": ["3462"],
        "utf16DecBytes": ["13410"],
        "utf32": "0x00003462",
        "utf32HexBytes": ["00003462"],
        "utf32DecBytes": ["13410"],
        "bidirectionalClass": "Left To Right (L)",
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": "㑢 (U+3462 CJK UNIFIED IDEOGRAPH-3462)",
        "bidirectionalControl": False,
        "pairedBracketType": "None (n)",
        "pairedBracketProperty": "㑢 (U+3462 CJK UNIFIED IDEOGRAPH-3462)",
        "decompositionType": "None (none)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "numericType": "None (None)",
        "numericValue": ["NaN"],
        "numericValueParsed": [],
        "joiningType": "Non Joining (U)",
        "joiningGroup": "No_Joining_Group",
        "joiningControl": False,
        "lineBreak": "Ideographic (ID)",
        "eastAsianWidth": "East Asian Wide (W)",
        "uppercase": False,
        "lowercase": False,
        "simpleUppercaseMapping": "㑢 (U+3462 CJK UNIFIED IDEOGRAPH-3462)",
        "simpleLowercaseMapping": "㑢 (U+3462 CJK UNIFIED IDEOGRAPH-3462)",
        "simpleTitlecaseMapping": "㑢 (U+3462 CJK UNIFIED IDEOGRAPH-3462)",
        "simpleCaseFolding": "㑢 (U+3462 CJK UNIFIED IDEOGRAPH-3462)",
        "script": "Han (Hani)",
        "scriptExtensions": ["Han (Hani)"],
        "hangulSyllableType": "Not Applicable (NA)",
        "indicSyllabicCategory": "Other",
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "character": "㑢",
        "name": "CJK UNIFIED IDEOGRAPH-3462",
        "description": "",
        "codepoint": "U+3462",
        "uriEncoded": "%E3%91%A2",
        "block": "CJK Unified Ideographs Extension A",
        "plane": "BMP",
        "age": "3.0",
        "generalCategory": "Other Letter (Lo)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#13410;", "&#x3462;"],
        "ideoFrequency": 0,
        "ideoGradeLevel": 0,
        "rsCountUnicode": "9.7",
        "rsCountKangxi": "",
        "totalStrokes": [9],
        "traditionalVariant": [""],
        "simplifiedVariant": [""],
        "zVariant": [""],
        "compatibilityVariant": [""],
        "semanticVariant": [""],
        "specializedSemanticVariant": [""],
        "spoofingVariant": [""],
        "accountingNumeric": "0",
        "primaryNumeric": "0",
        "otherNumeric": "0",
        "hangul": "",
        "cantonese": "koek3",
        "mandarin": "",
        "japaneseKun": "",
        "japaneseOn": "",
        "vietnamese": "",
        "ideographic": True,
        "unifiedIdeograph": True,
        "equivalentUnifiedIdeograph": "",
        "radical": False,
        "dash": False,
        "hyphen": False,
        "quotationMark": False,
        "terminalPunctuation": False,
        "sentenceTerminal": False,
        "diacritic": False,
        "extender": False,
        "softDotted": False,
        "alphabetic": True,
        "math": False,
        "hexDigit": False,
        "asciiHexDigit": False,
        "defaultIgnorableCodePoint": False,
        "logicalOrderException": False,
        "prependedConcatenationMark": False,
        "whiteSpace": False,
        "verticalOrientation": "Upright (U)",
        "regionalIndicator": False,
        "emoji": False,
        "emojiPresentation": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiComponent": False,
        "extendedPictographic": False,
    },
    "穩": {
        "utf8": "0xE7 0xA9 0xA9",
        "utf8HexBytes": ["E7", "A9", "A9"],
        "utf8DecBytes": ["231", "169", "169"],
        "utf16": "0x7A69",
        "utf16HexBytes": ["7A69"],
        "utf16DecBytes": ["31337"],
        "utf32": "0x00007A69",
        "utf32HexBytes": ["00007A69"],
        "utf32DecBytes": ["31337"],
        "bidirectionalClass": "Left To Right (L)",
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": "穩 (U+7A69 CJK UNIFIED IDEOGRAPH-7A69)",
        "bidirectionalControl": False,
        "pairedBracketType": "None (n)",
        "pairedBracketProperty": "穩 (U+7A69 CJK UNIFIED IDEOGRAPH-7A69)",
        "decompositionType": "None (none)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "numericType": "None (None)",
        "numericValue": ["NaN"],
        "numericValueParsed": [],
        "joiningType": "Non Joining (U)",
        "joiningGroup": "No_Joining_Group",
        "joiningControl": False,
        "lineBreak": "Ideographic (ID)",
        "eastAsianWidth": "East Asian Wide (W)",
        "uppercase": False,
        "lowercase": False,
        "simpleUppercaseMapping": "穩 (U+7A69 CJK UNIFIED IDEOGRAPH-7A69)",
        "simpleLowercaseMapping": "穩 (U+7A69 CJK UNIFIED IDEOGRAPH-7A69)",
        "simpleTitlecaseMapping": "穩 (U+7A69 CJK UNIFIED IDEOGRAPH-7A69)",
        "simpleCaseFolding": "穩 (U+7A69 CJK UNIFIED IDEOGRAPH-7A69)",
        "script": "Han (Hani)",
        "scriptExtensions": ["Han (Hani)"],
        "hangulSyllableType": "Not Applicable (NA)",
        "indicSyllabicCategory": "Other",
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "character": "穩",
        "name": "CJK UNIFIED IDEOGRAPH-7A69",
        "description": "stable, firm, solid, steady",
        "codepoint": "U+7A69",
        "uriEncoded": "%E7%A9%A9",
        "block": "CJK Unified Ideographs",
        "plane": "BMP",
        "age": "1.1",
        "generalCategory": "Other Letter (Lo)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#31337;", "&#x7A69;"],
        "ideoFrequency": 4,
        "ideoGradeLevel": 5,
        "rsCountUnicode": "115.14",
        "rsCountKangxi": "115.14",
        "totalStrokes": [19],
        "traditionalVariant": [""],
        "simplifiedVariant": ["稳 (U+7A33 CJK UNIFIED IDEOGRAPH-7A33)"],
        "zVariant": [""],
        "compatibilityVariant": [""],
        "semanticVariant": ["㒚 (U+349A CJK UNIFIED IDEOGRAPH-349A)"],
        "specializedSemanticVariant": ["文 (U+6587 CJK UNIFIED IDEOGRAPH-6587)"],
        "spoofingVariant": [""],
        "accountingNumeric": "0",
        "primaryNumeric": "0",
        "otherNumeric": "0",
        "hangul": "온:0N",
        "cantonese": "wan2",
        "mandarin": "wěn",
        "japaneseKun": "ODAYAKA",
        "japaneseOn": "ON",
        "vietnamese": "ủn",
        "ideographic": True,
        "unifiedIdeograph": True,
        "equivalentUnifiedIdeograph": "",
        "radical": False,
        "dash": False,
        "hyphen": False,
        "quotationMark": False,
        "terminalPunctuation": False,
        "sentenceTerminal": False,
        "diacritic": False,
        "extender": False,
        "softDotted": False,
        "alphabetic": True,
        "math": False,
        "hexDigit": False,
        "asciiHexDigit": False,
        "defaultIgnorableCodePoint": False,
        "logicalOrderException": False,
        "prependedConcatenationMark": False,
        "whiteSpace": False,
        "verticalOrientation": "Upright (U)",
        "regionalIndicator": False,
        "emoji": False,
        "emojiPresentation": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiComponent": False,
        "extendedPictographic": False,
    },
    "范": {
        "utf8": "0xE8 0x8C 0x83",
        "utf8HexBytes": ["E8", "8C", "83"],
        "utf8DecBytes": ["232", "140", "131"],
        "utf16": "0x8303",
        "utf16HexBytes": ["8303"],
        "utf16DecBytes": ["33539"],
        "utf32": "0x00008303",
        "utf32HexBytes": ["00008303"],
        "utf32DecBytes": ["33539"],
        "bidirectionalClass": "Left To Right (L)",
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": "范 (U+8303 CJK UNIFIED IDEOGRAPH-8303)",
        "bidirectionalControl": False,
        "pairedBracketType": "None (n)",
        "pairedBracketProperty": "范 (U+8303 CJK UNIFIED IDEOGRAPH-8303)",
        "decompositionType": "None (none)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "numericType": "None (None)",
        "numericValue": ["NaN"],
        "numericValueParsed": [],
        "joiningType": "Non Joining (U)",
        "joiningGroup": "No_Joining_Group",
        "joiningControl": False,
        "lineBreak": "Ideographic (ID)",
        "eastAsianWidth": "East Asian Wide (W)",
        "uppercase": False,
        "lowercase": False,
        "simpleUppercaseMapping": "范 (U+8303 CJK UNIFIED IDEOGRAPH-8303)",
        "simpleLowercaseMapping": "范 (U+8303 CJK UNIFIED IDEOGRAPH-8303)",
        "simpleTitlecaseMapping": "范 (U+8303 CJK UNIFIED IDEOGRAPH-8303)",
        "simpleCaseFolding": "范 (U+8303 CJK UNIFIED IDEOGRAPH-8303)",
        "script": "Han (Hani)",
        "scriptExtensions": ["Han (Hani)"],
        "hangulSyllableType": "Not Applicable (NA)",
        "indicSyllabicCategory": "Other",
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "character": "范",
        "name": "CJK UNIFIED IDEOGRAPH-8303",
        "description": "surname, bee-like insect",
        "codepoint": "U+8303",
        "uriEncoded": "%E8%8C%83",
        "block": "CJK Unified Ideographs",
        "plane": "BMP",
        "age": "1.1",
        "generalCategory": "Other Letter (Lo)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#33539;", "&#x8303;"],
        "ideoFrequency": 5,
        "ideoGradeLevel": 0,
        "rsCountUnicode": "140.5",
        "rsCountKangxi": "140.5",
        "totalStrokes": [8, 9],
        "traditionalVariant": ["範 (U+7BC4 CJK UNIFIED IDEOGRAPH-7BC4)", "范 (U+8303 CJK UNIFIED IDEOGRAPH-8303)"],
        "simplifiedVariant": ["范 (U+8303 CJK UNIFIED IDEOGRAPH-8303)"],
        "zVariant": [""],
        "compatibilityVariant": [""],
        "semanticVariant": [""],
        "specializedSemanticVariant": [""],
        "spoofingVariant": [""],
        "accountingNumeric": "0",
        "primaryNumeric": "0",
        "otherNumeric": "0",
        "hangul": "범:0N",
        "cantonese": "faan6",
        "mandarin": "fàn",
        "japaneseKun": "HACHI IGATA NORI",
        "japaneseOn": "HAN HON",
        "vietnamese": "",
        "ideographic": True,
        "unifiedIdeograph": True,
        "equivalentUnifiedIdeograph": "",
        "radical": False,
        "dash": False,
        "hyphen": False,
        "quotationMark": False,
        "terminalPunctuation": False,
        "sentenceTerminal": False,
        "diacritic": False,
        "extender": False,
        "softDotted": False,
        "alphabetic": True,
        "math": False,
        "hexDigit": False,
        "asciiHexDigit": False,
        "defaultIgnorableCodePoint": False,
        "logicalOrderException": False,
        "prependedConcatenationMark": False,
        "whiteSpace": False,
        "verticalOrientation": "Upright (U)",
        "regionalIndicator": False,
        "emoji": False,
        "emojiPresentation": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiComponent": False,
        "extendedPictographic": False,
    },
    "𑿀": {
        "character": "𑿀",
        "name": "TAMIL FRACTION ONE THREE-HUNDRED-AND-TWENTIETH",
        "codepoint": "U+11FC0",
        "uriEncoded": "%F0%91%BF%80",
        "block": "Tamil Supplement",
        "plane": "SMP",
        "age": "12.0",
        "generalCategory": "Other Number (No)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#73664;", "&#x11FC0;"],
        "utf8": "0xF0 0x91 0xBF 0x80",
        "utf8HexBytes": ["F0", "91", "BF", "80"],
        "utf8DecBytes": ["240", "145", "191", "128"],
        "utf16": "0xD807 0xDFC0",
        "utf16HexBytes": ["D807", "DFC0"],
        "utf16DecBytes": ["55303", "57280"],
        "utf32": "0x00011FC0",
        "utf32HexBytes": ["00011FC0"],
        "utf32DecBytes": ["73664"],
        "bidirectionalClass": "Left To Right (L)",
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": "𑿀 (U+11FC0 TAMIL FRACTION ONE THREE-HUNDRED-AND-TWENTIETH)",
        "bidirectionalControl": False,
        "pairedBracketType": "None (n)",
        "pairedBracketProperty": "𑿀 (U+11FC0 TAMIL FRACTION ONE THREE-HUNDRED-AND-TWENTIETH)",
        "decompositionType": "None (none)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "numericType": "Numeric (Nu)",
        "numericValue": ["1/320"],
        "numericValueParsed": [0.003125],
        "joiningType": "Non Joining (U)",
        "joiningGroup": "No_Joining_Group",
        "joiningControl": False,
        "lineBreak": "Ordinary Alphabetic And Symbol (AL)",
        "eastAsianWidth": "Neutral Not East Asian (N)",
        "uppercase": False,
        "lowercase": False,
        "simpleUppercaseMapping": "𑿀 (U+11FC0 TAMIL FRACTION ONE THREE-HUNDRED-AND-TWENTIETH)",
        "simpleLowercaseMapping": "𑿀 (U+11FC0 TAMIL FRACTION ONE THREE-HUNDRED-AND-TWENTIETH)",
        "simpleTitlecaseMapping": "𑿀 (U+11FC0 TAMIL FRACTION ONE THREE-HUNDRED-AND-TWENTIETH)",
        "simpleCaseFolding": "𑿀 (U+11FC0 TAMIL FRACTION ONE THREE-HUNDRED-AND-TWENTIETH)",
        "script": "Tamil (Taml)",
        "scriptExtensions": ["Tamil (Taml)"],
        "hangulSyllableType": "Not Applicable (NA)",
        "indicSyllabicCategory": "Other",
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "ideographic": False,
        "unifiedIdeograph": False,
        "equivalentUnifiedIdeograph": "",
        "radical": False,
        "dash": False,
        "hyphen": False,
        "quotationMark": False,
        "terminalPunctuation": False,
        "sentenceTerminal": False,
        "diacritic": False,
        "extender": False,
        "softDotted": False,
        "alphabetic": False,
        "math": False,
        "hexDigit": False,
        "asciiHexDigit": False,
        "defaultIgnorableCodePoint": False,
        "logicalOrderException": False,
        "prependedConcatenationMark": False,
        "whiteSpace": False,
        "verticalOrientation": "Rotated 90 degrees clockwise (R)",
        "regionalIndicator": False,
        "emoji": False,
        "emojiPresentation": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiComponent": False,
        "extendedPictographic": False,
    },
    "": {
        "character": "",
        "name": "<private-use-F800>",
        "codepoint": "U+F800",
        "uriEncoded": "%EF%A0%80",
        "block": "Private Use Area",
        "plane": "BMP",
        "age": "1.1",
        "generalCategory": "Private Use (Co)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#63488;", "&#xF800;"],
        "utf8": "0xEF 0xA0 0x80",
        "utf8HexBytes": ["EF", "A0", "80"],
        "utf8DecBytes": ["239", "160", "128"],
        "utf16": "0xF800",
        "utf16HexBytes": ["F800"],
        "utf16DecBytes": ["63488"],
        "utf32": "0x0000F800",
        "utf32HexBytes": ["0000F800"],
        "utf32DecBytes": ["63488"],
        "bidirectionalClass": "Left To Right (L)",
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": " (U+F800 <private-use-F800>)",
        "bidirectionalControl": False,
        "pairedBracketType": "None (n)",
        "pairedBracketProperty": "",
        "decompositionType": "None (none)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "numericType": "None (None)",
        "numericValue": [],
        "numericValueParsed": [],
        "joiningType": "Non Joining (U)",
        "joiningGroup": "",
        "joiningControl": False,
        "lineBreak": "Unknown (XX)",
        "eastAsianWidth": "East Asian Ambiguous (A)",
        "uppercase": False,
        "lowercase": False,
        "simpleUppercaseMapping": "",
        "simpleLowercaseMapping": "",
        "simpleTitlecaseMapping": "",
        "simpleCaseFolding": "",
        "script": "Unknown (Zzzz)",
        "scriptExtensions": ["Unknown (Zzzz)"],
        "hangulSyllableType": "Not Applicable (NA)",
        "indicSyllabicCategory": "",
        "indicMatraCategory": "",
        "indicPositionalCategory": "",
        "ideographic": False,
        "unifiedIdeograph": False,
        "equivalentUnifiedIdeograph": "",
        "radical": False,
        "dash": False,
        "hyphen": False,
        "quotationMark": False,
        "terminalPunctuation": False,
        "sentenceTerminal": False,
        "diacritic": False,
        "extender": False,
        "softDotted": False,
        "alphabetic": False,
        "math": False,
        "hexDigit": False,
        "asciiHexDigit": False,
        "defaultIgnorableCodePoint": False,
        "logicalOrderException": False,
        "prependedConcatenationMark": False,
        "whiteSpace": False,
        "verticalOrientation": "Upright (U)",
        "regionalIndicator": False,
        "emoji": False,
        "emojiPresentation": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiComponent": False,
        "extendedPictographic": False,
    },
    "￾": {
        "character": "￾",
        "name": "<noncharacter-FFFE>",
        "codepoint": "U+FFFE",
        "uriEncoded": "%EF%BF%BE",
        "block": "Specials",
        "plane": "BMP",
        "age": "1.1",
        "generalCategory": "Unassigned (Cn)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#65534;", "&#xFFFE;"],
        "utf8": "0xEF 0xBF 0xBE",
        "utf8HexBytes": ["EF", "BF", "BE"],
        "utf8DecBytes": ["239", "191", "190"],
        "utf16": "0xFFFE",
        "utf16HexBytes": ["FFFE"],
        "utf16DecBytes": ["65534"],
        "utf32": "0x0000FFFE",
        "utf32HexBytes": ["0000FFFE"],
        "utf32DecBytes": ["65534"],
        "bidirectionalClass": "Left To Right (L)",
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": "￾ (U+FFFE <noncharacter-FFFE>)",
        "bidirectionalControl": False,
        "pairedBracketType": "None (n)",
        "pairedBracketProperty": "",
        "decompositionType": "None (none)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "numericType": "None (None)",
        "numericValue": [],
        "numericValueParsed": [],
        "joiningType": "Non Joining (U)",
        "joiningGroup": "",
        "joiningControl": False,
        "lineBreak": "Unknown (XX)",
        "eastAsianWidth": "East Asian Ambiguous (A)",
        "uppercase": False,
        "lowercase": False,
        "simpleUppercaseMapping": "",
        "simpleLowercaseMapping": "",
        "simpleTitlecaseMapping": "",
        "simpleCaseFolding": "",
        "script": "Unknown (Zzzz)",
        "scriptExtensions": ["Unknown (Zzzz)"],
        "hangulSyllableType": "Not Applicable (NA)",
        "indicSyllabicCategory": "",
        "indicMatraCategory": "",
        "indicPositionalCategory": "",
        "ideographic": False,
        "unifiedIdeograph": False,
        "equivalentUnifiedIdeograph": "",
        "radical": False,
        "dash": False,
        "hyphen": False,
        "quotationMark": False,
        "terminalPunctuation": False,
        "sentenceTerminal": False,
        "diacritic": False,
        "extender": False,
        "softDotted": False,
        "alphabetic": False,
        "math": False,
        "hexDigit": False,
        "asciiHexDigit": False,
        "defaultIgnorableCodePoint": False,
        "logicalOrderException": False,
        "prependedConcatenationMark": False,
        "whiteSpace": False,
        "verticalOrientation": "Upright (U)",
        "regionalIndicator": False,
        "emoji": False,
        "emojiPresentation": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiComponent": False,
        "extendedPictographic": False,
    },
    "🇦": {
        "character": "🇦",
        "name": "REGIONAL INDICATOR SYMBOL LETTER A",
        "codepoint": "U+1F1E6",
        "uriEncoded": "%F0%9F%87%A6",
        "block": "Enclosed Alphanumeric Supplement",
        "plane": "SMP",
        "age": "6.0",
        "generalCategory": "Other Symbol (So)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#127462;", "&#x1F1E6;"],
        "utf8": "0xF0 0x9F 0x87 0xA6",
        "utf8HexBytes": ["F0", "9F", "87", "A6"],
        "utf8DecBytes": ["240", "159", "135", "166"],
        "utf16": "0xD83C 0xDDE6",
        "utf16HexBytes": ["D83C", "DDE6"],
        "utf16DecBytes": ["55356", "56806"],
        "utf32": "0x0001F1E6",
        "utf32HexBytes": ["0001F1E6"],
        "utf32DecBytes": ["127462"],
        "bidirectionalClass": "Left To Right (L)",
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": "🇦 (U+1F1E6 REGIONAL INDICATOR SYMBOL LETTER A)",
        "bidirectionalControl": False,
        "pairedBracketType": "None (n)",
        "pairedBracketProperty": "🇦 (U+1F1E6 REGIONAL INDICATOR SYMBOL LETTER A)",
        "decompositionType": "None (none)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "numericType": "None (None)",
        "numericValue": ["NaN"],
        "numericValueParsed": [],
        "joiningType": "Non Joining (U)",
        "joiningGroup": "No_Joining_Group",
        "joiningControl": False,
        "lineBreak": "Unknown (XX)",
        "eastAsianWidth": "Neutral Not East Asian (N)",
        "uppercase": False,
        "lowercase": False,
        "simpleUppercaseMapping": "🇦 (U+1F1E6 REGIONAL INDICATOR SYMBOL LETTER A)",
        "simpleLowercaseMapping": "🇦 (U+1F1E6 REGIONAL INDICATOR SYMBOL LETTER A)",
        "simpleTitlecaseMapping": "🇦 (U+1F1E6 REGIONAL INDICATOR SYMBOL LETTER A)",
        "simpleCaseFolding": "🇦 (U+1F1E6 REGIONAL INDICATOR SYMBOL LETTER A)",
        "script": "Common (Zyyy)",
        "scriptExtensions": ["Common (Zyyy)"],
        "hangulSyllableType": "Not Applicable (NA)",
        "indicSyllabicCategory": "Other",
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "ideographic": False,
        "unifiedIdeograph": False,
        "equivalentUnifiedIdeograph": "",
        "radical": False,
        "dash": False,
        "hyphen": False,
        "quotationMark": False,
        "terminalPunctuation": False,
        "sentenceTerminal": False,
        "diacritic": False,
        "extender": False,
        "softDotted": False,
        "alphabetic": False,
        "math": False,
        "hexDigit": False,
        "asciiHexDigit": False,
        "defaultIgnorableCodePoint": False,
        "logicalOrderException": False,
        "prependedConcatenationMark": False,
        "whiteSpace": False,
        "verticalOrientation": "Upright (U)",
        "regionalIndicator": True,
        "emoji": True,
        "emojiPresentation": True,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiComponent": True,
        "extendedPictographic": False,
    },
    "🐍": {
        "character": "🐍",
        "name": "SNAKE",
        "codepoint": "U+1F40D",
        "uriEncoded": "%F0%9F%90%8D",
        "block": "Miscellaneous Symbols and Pictographs",
        "plane": "SMP",
        "age": "6.0",
        "generalCategory": "Other Symbol (So)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#128013;", "&#x1F40D;"],
        "utf8": "0xF0 0x9F 0x90 0x8D",
        "utf8HexBytes": ["F0", "9F", "90", "8D"],
        "utf8DecBytes": ["240", "159", "144", "141"],
        "utf16": "0xD83D 0xDC0D",
        "utf16HexBytes": ["D83D", "DC0D"],
        "utf16DecBytes": ["55357", "56333"],
        "utf32": "0x0001F40D",
        "utf32HexBytes": ["0001F40D"],
        "utf32DecBytes": ["128013"],
        "bidirectionalClass": "Other Neutral (ON)",
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": "🐍 (U+1F40D SNAKE)",
        "bidirectionalControl": False,
        "pairedBracketType": "None (n)",
        "pairedBracketProperty": "🐍 (U+1F40D SNAKE)",
        "decompositionType": "None (none)",
        "NFC_QC": "Yes",
        "NFD_QC": "Yes",
        "NFKC_QC": "Yes",
        "NFKD_QC": "Yes",
        "numericType": "None (None)",
        "numericValue": ["NaN"],
        "numericValueParsed": [],
        "joiningType": "Non Joining (U)",
        "joiningGroup": "No_Joining_Group",
        "joiningControl": False,
        "lineBreak": "Ideographic (ID)",
        "eastAsianWidth": "East Asian Wide (W)",
        "uppercase": False,
        "lowercase": False,
        "simpleUppercaseMapping": "🐍 (U+1F40D SNAKE)",
        "simpleLowercaseMapping": "🐍 (U+1F40D SNAKE)",
        "simpleTitlecaseMapping": "🐍 (U+1F40D SNAKE)",
        "simpleCaseFolding": "🐍 (U+1F40D SNAKE)",
        "script": "Common (Zyyy)",
        "scriptExtensions": ["Common (Zyyy)"],
        "hangulSyllableType": "Not Applicable (NA)",
        "indicSyllabicCategory": "Other",
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "ideographic": False,
        "unifiedIdeograph": False,
        "equivalentUnifiedIdeograph": "",
        "radical": False,
        "dash": False,
        "hyphen": False,
        "quotationMark": False,
        "terminalPunctuation": False,
        "sentenceTerminal": False,
        "diacritic": False,
        "extender": False,
        "softDotted": False,
        "alphabetic": False,
        "math": False,
        "hexDigit": False,
        "asciiHexDigit": False,
        "defaultIgnorableCodePoint": False,
        "logicalOrderException": False,
        "prependedConcatenationMark": False,
        "whiteSpace": False,
        "verticalOrientation": "Upright (U)",
        "regionalIndicator": False,
        "emoji": True,
        "emojiPresentation": True,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiComponent": False,
        "extendedPictographic": True,
    },
}


def get_all_prop_names():
    prop_names = [prop_group.normalized for prop_group in CharPropertyGroup if prop_group != CharPropertyGroup.NONE]
    prop_aliases = [prop_group.short_alias for prop_group in CharPropertyGroup if prop_group.has_alias]
    return list(set(prop_names + prop_aliases))


ALL_PROP_GROUP_NAMES = get_all_prop_names()

INVALID_PROP_GROUP_NAMES = {
    "detail": "3 values provided for the 'show_props' parameter are invalid: ['foo', 'bar', 'baz']"
}
