# flake8: noqa
from app.docs.dependencies.filter_tables import (
    BIDI_CLASS_VALUES_TABLE,
    BLOCK_NAME_VALUES_TABLE,
    BLOCK_NAME_NO_LEGEND_TABLE,
    CCC_VALUES_TABLE,
    CHAR_FLAGS_TABLE,
    DECOMP_TYPE_VALUES_TABLE,
    GENERAL_CATEGORY_VALUES_TABLE,
    JOINING_TYPES_TABLE,
    LINE_BREAK_TYPE_VALUES_TABLE,
    NUMERIC_TYPES_TABLE,
    PROPERTY_GROUP_VALUES_TABLE,
    SCRIPT_CODE_VALUES_TABLE,
    UNICODE_AGE_VALUES_TABLE,
)
