SEARCH_TERM_HOUSE_PAGE_1_OF_2 = {
    "url": "/v1/characters/search",
    "query": "house",
    "hasMore": True,
    "currentPage": 1,
    "nextPage": 2,
    "totalResults": 13,
    "results": [
        {
            "character": "⌂",
            "name": "HOUSE",
            "description": None,
            "codepoint": "U+2302",
            "uriEncoded": "%E2%8C%82",
            "score": 100.0,
        },
        {
            "character": "⛯",
            "name": "MAP SYMBOL FOR LIGHTHOUSE",
            "description": None,
            "codepoint": "U+26EF",
            "uriEncoded": "%E2%9B%AF",
            "score": 90.0,
        },
        {
            "character": "𖧝",
            "name": "BAMUM LETTER PHASE-E NDAA MY HOUSE",
            "description": None,
            "codepoint": "U+169DD",
            "uriEncoded": "%F0%96%A7%9D",
            "score": 90.0,
        },
        {
            "character": "🏘",
            "name": "HOUSE BUILDINGS",
            "description": None,
            "codepoint": "U+1F3D8",
            "uriEncoded": "%F0%9F%8F%98",
            "score": 90.0,
        },
        {
            "character": "🏚",
            "name": "DERELICT HOUSE BUILDING",
            "description": None,
            "codepoint": "U+1F3DA",
            "uriEncoded": "%F0%9F%8F%9A",
            "score": 90.0,
        },
        {
            "character": "🏠",
            "name": "HOUSE BUILDING",
            "description": None,
            "codepoint": "U+1F3E0",
            "uriEncoded": "%F0%9F%8F%A0",
            "score": 90.0,
        },
        {
            "character": "🏡",
            "name": "HOUSE WITH GARDEN",
            "description": None,
            "codepoint": "U+1F3E1",
            "uriEncoded": "%F0%9F%8F%A1",
            "score": 90.0,
        },
        {
            "character": "🐁",
            "name": "MOUSE",
            "description": None,
            "codepoint": "U+1F401",
            "uriEncoded": "%F0%9F%90%81",
            "score": 80.0,
        },
        {
            "character": "🐎",
            "name": "HORSE",
            "description": None,
            "codepoint": "U+1F40E",
            "uriEncoded": "%F0%9F%90%8E",
            "score": 80.0,
        },
        {
            "character": "🖦",
            "name": "KEYBOARD AND MOUSE",
            "description": None,
            "codepoint": "U+1F5A6",
            "uriEncoded": "%F0%9F%96%A6",
            "score": 80.0,
        },
    ],
}

SEARCH_TERM_HOUSE_PAGE_2_OF_2 = {
    "url": "/v1/characters/search",
    "query": "house",
    "hasMore": False,
    "currentPage": 2,
    "totalResults": 13,
    "results": [
        {
            "character": "🖯",
            "name": "ONE BUTTON MOUSE",
            "description": None,
            "codepoint": "U+1F5AF",
            "uriEncoded": "%F0%9F%96%AF",
            "score": 80.0,
        },
        {
            "character": "🖰",
            "name": "TWO BUTTON MOUSE",
            "description": None,
            "codepoint": "U+1F5B0",
            "uriEncoded": "%F0%9F%96%B0",
            "score": 80.0,
        },
        {
            "character": "🖱",
            "name": "THREE BUTTON MOUSE",
            "description": None,
            "codepoint": "U+1F5B1",
            "uriEncoded": "%F0%9F%96%B1",
            "score": 80.0,
        },
    ],
}

SEARCH_TERM_HOUSE_PAGE_3_OF_2 = {"detail": "Request for page #3 is invalid since there are 2 total pages."}

SEARCH_TERM_HOME = {
    "url": "/v1/characters/search",
    "query": "home",
    "hasMore": False,
    "currentPage": 0,
    "totalResults": 0,
    "results": [],
}
