import pytest
from fastapi.testclient import TestClient
from humps import camelize

from app.db.constants import CHARACTER_PROPERTY_GROUPS
from app.main import app
from app.schemas.enums.property_group import CharPropertyGroup

client = TestClient(app)

ALL_CHARACTER_PROPERTIES = {
    0: {
        "character": "∑",
        "name": "N-ARY SUMMATION",
        "codepoint": "U+2211",
        "uriEncoded": "%E2%88%91",
        "block": "Mathematical Operators",
        "plane": "BMP",
        "age": "1.1",
        "generalCategory": "Math Symbol (Sm)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#8721;", "&#x2211;", "&sum;"],
        "utf8": "0xE2 0x88 0x91",
        "utf8HexBytes": ["E2", "88", "91"],
        "utf8DecBytes": ["226", "136", "145"],
        "utf16": "0x2211",
        "utf16HexBytes": ["2211"],
        "utf16DecBytes": ["8721"],
        "utf32": "0x00002211",
        "utf32HexBytes": ["00002211"],
        "utf32DecBytes": ["8721"],
        "bidirectionalClass": "Other Neutral (ON)",
        "bidirectionalIsMirrored": True,
        "bidirectionalMirroringGlyph": "",
        "bidirectionalControl": False,
        "pairedBracketType": "None (n)",
        "pairedBracketProperty": "∑ (U+2211)",
        "decompositionType": "None (none)",
        "decompositionMapping": ["∑ (U+2211)"],
        "compositionExclusion": False,
        "fullCompositionExclusion": False,
        "numericType": "None (None)",
        "numericValue": "NaN",
        "numericValueParsed": None,
        "joiningClass": "Non Joining (U)",
        "joiningGroup": "No_Joining_Group",
        "joiningControl": False,
        "lineBreak": "Ambiguous (Alphabetic Or Ideographic) (AI)",
        "eastAsianWidth": "East Asian Ambiguous (A)",
        "uppercase": False,
        "lowercase": False,
        "simpleUppercaseMapping": "∑ (U+2211)",
        "simpleLowercaseMapping": "∑ (U+2211)",
        "simpleTitlecaseMapping": "∑ (U+2211)",
        "simpleCaseFolding": "∑ (U+2211)",
        "otherUppercase": False,
        "otherLowercase": False,
        "otherUppercaseMapping": ["∑ (U+2211)"],
        "otherLowercaseMapping": ["∑ (U+2211)"],
        "otherTitlecaseMapping": ["∑ (U+2211)"],
        "otherCaseFolding": ["∑ (U+2211)"],
        "script": "Common (Zyyy)",
        "scriptExtension": ["Common (Zyyy)"],
        "hangulSyllableType": "Not Applicable (NA)",
        "jamoShortName": "",
        "indicSyllabicCategory": "Other",
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "dash": False,
        "hyphen": False,
        "quotationMark": False,
        "terminalPunctuation": False,
        "sentenceTerminal": False,
        "diacritic": False,
        "extender": False,
        "softDotted": False,
        "alphabetic": False,
        "otherAlphabetic": False,
        "math": False,
        "otherMath": True,
        "hexDigit": False,
        "asciiHexDigit": False,
        "defaultIgnorableCodePoint": False,
        "otherDefaultIgnorableCodePoint": False,
        "logicalOrderException": False,
        "prependedConcatenationMark": False,
        "whiteSpace": False,
        "verticalOrientation": "Rotated 90 degrees clockwise (R)",
        "regionalIndicator": False,
        "emoji": False,
        "emojiPresentation": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiComponent": False,
        "extendedPictographic": False,
    },
    1: {
        "character": "ཀྵ",
        "name": "TIBETAN LETTER KSSA",
        "codepoint": "U+0F69",
        "uriEncoded": "%E0%BD%A9",
        "block": "Tibetan",
        "plane": "BMP",
        "age": "2.0",
        "generalCategory": "Other Letter (Lo)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#3945;", "&#xF69;"],
        "utf8": "0xE0 0xBD 0xA9",
        "utf8HexBytes": ["E0", "BD", "A9"],
        "utf8DecBytes": ["224", "189", "169"],
        "utf16": "0x0F69",
        "utf16HexBytes": ["0F69"],
        "utf16DecBytes": ["3945"],
        "utf32": "0x00000F69",
        "utf32HexBytes": ["00000F69"],
        "utf32DecBytes": ["3945"],
        "bidirectionalClass": "Left To Right (L)",
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": "",
        "bidirectionalControl": False,
        "pairedBracketType": "None (n)",
        "pairedBracketProperty": "ཀྵ (U+0F69)",
        "decompositionType": "Canonical (can)",
        "decompositionMapping": ["ཀ (U+0F40)", "ྵ (U+0FB5)"],
        "compositionExclusion": True,
        "fullCompositionExclusion": True,
        "numericType": "None (None)",
        "numericValue": "NaN",
        "numericValueParsed": None,
        "joiningClass": "Non Joining (U)",
        "joiningGroup": "No_Joining_Group",
        "joiningControl": False,
        "lineBreak": "Ordinary Alphabetic And Symbol (AL)",
        "eastAsianWidth": "Neutral Not East Asian (N)",
        "uppercase": False,
        "lowercase": False,
        "simpleUppercaseMapping": "ཀྵ (U+0F69)",
        "simpleLowercaseMapping": "ཀྵ (U+0F69)",
        "simpleTitlecaseMapping": "ཀྵ (U+0F69)",
        "simpleCaseFolding": "ཀྵ (U+0F69)",
        "otherUppercase": False,
        "otherLowercase": False,
        "otherUppercaseMapping": ["ཀྵ (U+0F69)"],
        "otherLowercaseMapping": ["ཀྵ (U+0F69)"],
        "otherTitlecaseMapping": ["ཀྵ (U+0F69)"],
        "otherCaseFolding": ["ཀྵ (U+0F69)"],
        "script": "Tibetan (Tibt)",
        "scriptExtension": ["Tibetan (Tibt)"],
        "hangulSyllableType": "Not Applicable (NA)",
        "jamoShortName": "",
        "indicSyllabicCategory": "Consonant",
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "dash": False,
        "hyphen": False,
        "quotationMark": False,
        "terminalPunctuation": False,
        "sentenceTerminal": False,
        "diacritic": False,
        "extender": False,
        "softDotted": False,
        "alphabetic": False,
        "otherAlphabetic": True,
        "math": False,
        "otherMath": False,
        "hexDigit": False,
        "asciiHexDigit": False,
        "defaultIgnorableCodePoint": False,
        "otherDefaultIgnorableCodePoint": False,
        "logicalOrderException": False,
        "prependedConcatenationMark": False,
        "whiteSpace": False,
        "verticalOrientation": "Rotated 90 degrees clockwise (R)",
        "regionalIndicator": False,
        "emoji": False,
        "emojiPresentation": False,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiComponent": False,
        "extendedPictographic": False,
    },
    2: {
        "character": "🐍",
        "name": "SNAKE",
        "codepoint": "U+1F40D",
        "uriEncoded": "%F0%9F%90%8D",
        "block": "Miscellaneous Symbols and Pictographs",
        "plane": "SMP",
        "age": "6.0",
        "generalCategory": "Other Symbol (So)",
        "combiningClass": "Not Reordered (0)",
        "htmlEntities": ["&#128013;", "&#x1F40D;"],
        "utf8": "0xF0 0x9F 0x90 0x8D",
        "utf8HexBytes": ["F0", "9F", "90", "8D"],
        "utf8DecBytes": ["240", "159", "144", "141"],
        "utf16": "0xD83D 0xDC0D",
        "utf16HexBytes": ["D83D", "DC0D"],
        "utf16DecBytes": ["55357", "56333"],
        "utf32": "0x0001F40D",
        "utf32HexBytes": ["0001F40D"],
        "utf32DecBytes": ["128013"],
        "bidirectionalClass": "Other Neutral (ON)",
        "bidirectionalIsMirrored": False,
        "bidirectionalMirroringGlyph": "",
        "bidirectionalControl": False,
        "pairedBracketType": "None (n)",
        "pairedBracketProperty": "🐍 (U+1F40D)",
        "decompositionType": "None (none)",
        "decompositionMapping": ["🐍 (U+1F40D)"],
        "compositionExclusion": False,
        "fullCompositionExclusion": False,
        "numericType": "None (None)",
        "numericValue": "NaN",
        "numericValueParsed": None,
        "joiningClass": "Non Joining (U)",
        "joiningGroup": "No_Joining_Group",
        "joiningControl": False,
        "lineBreak": "Ideographic (ID)",
        "eastAsianWidth": "East Asian Wide (W)",
        "uppercase": False,
        "lowercase": False,
        "simpleUppercaseMapping": "🐍 (U+1F40D)",
        "simpleLowercaseMapping": "🐍 (U+1F40D)",
        "simpleTitlecaseMapping": "🐍 (U+1F40D)",
        "simpleCaseFolding": "🐍 (U+1F40D)",
        "otherUppercase": False,
        "otherLowercase": False,
        "otherUppercaseMapping": ["🐍 (U+1F40D)"],
        "otherLowercaseMapping": ["🐍 (U+1F40D)"],
        "otherTitlecaseMapping": ["🐍 (U+1F40D)"],
        "otherCaseFolding": ["🐍 (U+1F40D)"],
        "script": "Common (Zyyy)",
        "scriptExtension": ["Common (Zyyy)"],
        "hangulSyllableType": "Not Applicable (NA)",
        "jamoShortName": "",
        "indicSyllabicCategory": "Other",
        "indicMatraCategory": "NA",
        "indicPositionalCategory": "NA",
        "dash": False,
        "hyphen": False,
        "quotationMark": False,
        "terminalPunctuation": False,
        "sentenceTerminal": False,
        "diacritic": False,
        "extender": False,
        "softDotted": False,
        "alphabetic": False,
        "otherAlphabetic": False,
        "math": False,
        "otherMath": False,
        "hexDigit": False,
        "asciiHexDigit": False,
        "defaultIgnorableCodePoint": False,
        "otherDefaultIgnorableCodePoint": False,
        "logicalOrderException": False,
        "prependedConcatenationMark": False,
        "whiteSpace": False,
        "verticalOrientation": "Upright (U)",
        "regionalIndicator": False,
        "emoji": True,
        "emojiPresentation": True,
        "emojiModifier": False,
        "emojiModifierBase": False,
        "emojiComponent": False,
        "extendedPictographic": True,
    },
}


def get_character_properties(prop_group, prop_data):
    minimum = get_prop_group(CharPropertyGroup.Minimum, prop_data)
    char_props = {}
    if prop_group == CharPropertyGroup.All:
        for group in CharPropertyGroup:
            if group != CharPropertyGroup.All:
                char_props.update(get_prop_group(group, prop_data))
    else:
        char_props = get_prop_group(prop_group, prop_data)
    return char_props | minimum


def get_prop_group(prop_group, prop_data):
    return {
        camelize(prop_details["name_out"]): prop_data[camelize(prop_details["name_out"])]
        for prop_details in CHARACTER_PROPERTY_GROUPS[prop_group]
    }


@pytest.mark.parametrize("char_index", [0, 1, 2])
def test_get_character_details_default(char_index):
    char = ALL_CHARACTER_PROPERTIES[char_index]["character"]
    response = client.get(f"/v1/characters/{char}")
    assert response.status_code == 200
    assert response.json() == [
        get_character_properties(CharPropertyGroup.Minimum, ALL_CHARACTER_PROPERTIES[char_index])
    ]


@pytest.mark.parametrize(
    "prop_group",
    [
        CharPropertyGroup.All,
        CharPropertyGroup.Minimum,
        CharPropertyGroup.Basic,
        CharPropertyGroup.UTF8,
        CharPropertyGroup.UTF16,
        CharPropertyGroup.UTF32,
        CharPropertyGroup.Bidirectionality,
        CharPropertyGroup.Decomposition,
        CharPropertyGroup.Numeric,
        CharPropertyGroup.Joining,
        CharPropertyGroup.Linebreak,
        CharPropertyGroup.East_Asian_Width,
        CharPropertyGroup.Case,
        CharPropertyGroup.Script,
        CharPropertyGroup.Hangul,
        CharPropertyGroup.Indic,
        CharPropertyGroup.Function_and_Graphic,
        CharPropertyGroup.Emoji,
    ],
)
@pytest.mark.parametrize("char_index", [0, 1, 2])
def test_get_character_details_show_props(prop_group, char_index):
    char = ALL_CHARACTER_PROPERTIES[char_index]["character"]
    response = client.get(f"/v1/characters/{char}?show_props={prop_group.name}")
    assert response.status_code == 200
    assert response.json() == [get_character_properties(prop_group, ALL_CHARACTER_PROPERTIES[char_index])]
